//! Excellon drill file export for Volt PCB boards.
//!
//! Generates industry-standard Excellon drill files (`.drl`) for PCB
//! fabrication. Two kinds of files are produced:
//!
//! - **PTH** — plated through-holes: vias and THT pad holes
//! - **NPTH** — non-plated holes: mounting holes, tooling holes, cutouts
//!
//! The Excellon format is a simple text format understood by virtually
//! every CNC drill machine and every board fabrication shop. Volt emits
//! the metric variant with trailing-zero suppression and coordinates
//! expressed in microns (µm) as signed integers.

use std::path::{Path, PathBuf};

use crate::gerber::{transform_point, BoardLibrary};
use volt_core::common::PadSide;
use volt_core::project::{Board, FabricationOutputSettings};

// ═══════════════════════════════════════════════════════════════════════════
// ExcellonWriter — low-level Excellon format writer
// ═══════════════════════════════════════════════════════════════════════════

/// A single drill tool definition (diameter in millimetres).
#[derive(Debug, Clone, Copy)]
struct DrillTool {
    diameter: f64,
}

/// Tolerance used when matching existing tools by diameter (millimetres).
const TOOL_MATCH_TOLERANCE_MM: f64 = 0.001;

/// Low-level Excellon file writer.
///
/// Accumulates tool definitions and drill hits, then emits a complete
/// Excellon file via [`ExcellonWriter::to_string`].
pub struct ExcellonWriter {
    tools: Vec<DrillTool>,
    /// Each hit is `(tool_index, x_mm, y_mm)` where `tool_index` is the
    /// 1-based tool number (T1, T2, ...).
    hits: Vec<(usize, f64, f64)>,
}

impl ExcellonWriter {
    /// Create an empty writer with no tools and no hits.
    pub fn new() -> Self {
        Self {
            tools: Vec::new(),
            hits: Vec::new(),
        }
    }

    /// Register a drill tool with the given diameter (in millimetres) and
    /// return its 1-based tool number.
    pub fn add_tool(&mut self, diameter: f64) -> usize {
        self.tools.push(DrillTool { diameter });
        self.tools.len()
    }

    /// Find an existing tool whose diameter matches `diameter` within
    /// 0.001 mm; otherwise, create a new tool. Returns the 1-based tool
    /// number in either case.
    pub fn find_or_add_tool(&mut self, diameter: f64) -> usize {
        for (i, tool) in self.tools.iter().enumerate() {
            if (tool.diameter - diameter).abs() <= TOOL_MATCH_TOLERANCE_MM {
                return i + 1;
            }
        }
        self.add_tool(diameter)
    }

    /// Record a drill hit using the given 1-based tool number.
    pub fn add_hit(&mut self, tool: usize, x: f64, y: f64) {
        self.hits.push((tool, x, y));
    }

    /// Number of registered tools.
    pub fn tool_count(&self) -> usize {
        self.tools.len()
    }

    /// Number of drill hits recorded.
    pub fn hit_count(&self) -> usize {
        self.hits.len()
    }

    /// Generate the full Excellon file content as a string.
    ///
    /// The output conforms to the metric variant with trailing zero
    /// suppression (`METRIC,TZ`). Coordinates are emitted as signed
    /// integers in microns (mm × 1000).
    pub fn to_string(&self) -> String {
        let mut out = String::with_capacity(256 + 24 * self.hits.len());

        // ── Header ──────────────────────────────────────────────────────
        out.push_str("M48\n");
        out.push_str("; Generated by Volt EDA\n");
        out.push_str("METRIC,TZ\n");
        out.push_str("FMAT,2\n");
        for (i, tool) in self.tools.iter().enumerate() {
            // T{n}C{diameter}
            out.push_str(&format!("T{}C{:.3}\n", i + 1, tool.diameter));
        }
        out.push_str("%\n");

        // ── Body: group hits by tool, in tool order ─────────────────────
        // Group hits by tool so each tool appears once per run.
        let mut current_tool: Option<usize> = None;
        for tool_idx in 1..=self.tools.len() {
            for (t, x, y) in &self.hits {
                if *t != tool_idx {
                    continue;
                }
                if current_tool != Some(tool_idx) {
                    out.push_str(&format!("T{}\n", tool_idx));
                    current_tool = Some(tool_idx);
                }
                out.push_str(&format!("X{}Y{}\n", format_coord(*x), format_coord(*y)));
            }
        }

        // ── Footer ──────────────────────────────────────────────────────
        out.push_str("M30\n");
        out
    }
}

impl Default for ExcellonWriter {
    fn default() -> Self {
        Self::new()
    }
}

/// Convert a millimetre value to an Excellon coordinate string
/// (signed integer in microns; trailing zeros retained).
fn format_coord(mm: f64) -> String {
    let value = (mm * 1000.0).round() as i64;
    value.to_string()
}

// ═══════════════════════════════════════════════════════════════════════════
// Hit collection helpers
// ═══════════════════════════════════════════════════════════════════════════

/// A drill hit collected from board data, prior to tool grouping.
#[derive(Debug, Clone, Copy)]
struct RawHit {
    diameter: f64,
    x: f64,
    y: f64,
}

/// Collect all plated through-hole drill hits from a board:
/// - Vias (from every net segment)
/// - THT pad holes on footprint pads (side = ThroughHole)
fn collect_pth_hits(board: &Board, library: &dyn BoardLibrary) -> Result<Vec<RawHit>, String> {
    let mut hits: Vec<RawHit> = Vec::new();

    // ── Vias ────────────────────────────────────────────────────────────
    for seg in &board.net_segments {
        for via in &seg.vias {
            if via.drill <= 0.0 {
                continue;
            }
            hits.push(RawHit {
                diameter: via.drill,
                x: via.position.x,
                y: via.position.y,
            });
        }
    }

    // ── THT pad holes on device footprints ──────────────────────────────
    for dev in &board.devices {
        let Some(lib_dev) = library.get_device(&dev.lib_device) else {
            return Err(format!(
                "library device not found for board device {}",
                dev.component
            ));
        };
        let Some(pkg) = library.get_package(&lib_dev.package) else {
            return Err(format!("library package {} not found", lib_dev.package));
        };
        let Some(footprint) = pkg
            .footprints
            .iter()
            .find(|f| f.uuid == dev.lib_footprint)
        else {
            return Err(format!(
                "footprint {} not found in package",
                dev.lib_footprint
            ));
        };
        for fp_pad in &footprint.pads {
            // Only THT pads have plated drill holes.
            if fp_pad.side != PadSide::ThroughHole {
                continue;
            }
            for hole in &fp_pad.holes {
                if hole.diameter <= 0.0 {
                    continue;
                }
                // Hole location: if the hole has a path, use its first
                // vertex; otherwise, the pad centre. All footprint-local
                // positions must be transformed into board coordinates.
                let (local_x, local_y) = if let Some(first) = hole.path.first() {
                    (
                        fp_pad.position.x + first.position.x,
                        fp_pad.position.y + first.position.y,
                    )
                } else {
                    (fp_pad.position.x, fp_pad.position.y)
                };
                let (x, y) = transform_point(local_x, local_y, dev);
                hits.push(RawHit {
                    diameter: hole.diameter,
                    x,
                    y,
                });
            }
        }
    }

    Ok(hits)
}

/// Collect all non-plated through-hole drill hits from a board's
/// standalone `holes` list.
fn collect_npth_hits(board: &Board) -> Vec<RawHit> {
    let mut hits = Vec::new();
    for hole in &board.holes {
        if hole.diameter <= 0.0 {
            continue;
        }
        // Use the first vertex of the hole path as its position. A hole
        // with no path is ignored (invalid geometry).
        let Some(first) = hole.path.first() else {
            continue;
        };
        hits.push(RawHit {
            diameter: hole.diameter,
            x: first.position.x,
            y: first.position.y,
        });
    }
    hits
}

/// Build an [`ExcellonWriter`] from a list of raw hits, grouping by
/// diameter into tools sorted in ascending order.
fn build_writer(hits: &[RawHit]) -> ExcellonWriter {
    // Collect unique diameters (within tolerance) and sort ascending.
    let mut diameters: Vec<f64> = Vec::new();
    'outer: for h in hits {
        for d in &diameters {
            if (h.diameter - d).abs() <= TOOL_MATCH_TOLERANCE_MM {
                continue 'outer;
            }
        }
        diameters.push(h.diameter);
    }
    diameters.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));

    let mut writer = ExcellonWriter::new();
    for d in &diameters {
        writer.add_tool(*d);
    }

    // Assign each hit to its matching tool.
    for h in hits {
        let tool = writer.find_or_add_tool(h.diameter);
        writer.add_hit(tool, h.x, h.y);
    }
    writer
}

// ═══════════════════════════════════════════════════════════════════════════
// Public export API
// ═══════════════════════════════════════════════════════════════════════════

/// Export the PTH (plated through-hole) drill file as an Excellon string.
///
/// Includes every via on the board (outer through vias and blind/buried
/// vias alike — drilling is independent of layer span for this purpose)
/// and every drill hole on every THT footprint pad.
pub fn export_pth_drills(
    board: &Board,
    library: &dyn BoardLibrary,
) -> Result<String, String> {
    let hits = collect_pth_hits(board, library)?;
    let writer = build_writer(&hits);
    Ok(writer.to_string())
}

/// Export the NPTH (non-plated) drill file as an Excellon string.
///
/// Includes every entry in `board.holes` (mounting holes, tooling
/// holes, cutouts, etc.).
pub fn export_npth_drills(board: &Board) -> Result<String, String> {
    let hits = collect_npth_hits(board);
    let writer = build_writer(&hits);
    Ok(writer.to_string())
}

/// Export a merged drill file containing both plated and non-plated
/// holes. The merged file does not distinguish between the two kinds
/// of holes; if a fabricator requires separate PTH/NPTH files, leave
/// `merge_drills` disabled.
pub fn export_merged_drills(
    board: &Board,
    library: &dyn BoardLibrary,
) -> Result<String, String> {
    let mut hits = collect_pth_hits(board, library)?;
    hits.extend(collect_npth_hits(board));
    Ok(build_writer(&hits).to_string())
}

// ═══════════════════════════════════════════════════════════════════════════
// File-level orchestration
// ═══════════════════════════════════════════════════════════════════════════

/// Summary of files written by [`export_all_drills`].
#[derive(Debug)]
pub struct DrillSummary {
    pub files: Vec<DrillFile>,
    pub pth_hole_count: usize,
    pub npth_hole_count: usize,
}

/// A single exported drill file.
#[derive(Debug)]
pub struct DrillFile {
    pub path: PathBuf,
    pub kind: DrillFileKind,
    pub hole_count: usize,
}

/// Which kind of drill file was written.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DrillFileKind {
    Pth,
    Npth,
    Merged,
}

/// Export all drill files for the board to `output_dir`.
///
/// Always writes a PTH file and an NPTH file, using the suffixes
/// `drills_pth_suffix` and `drills_npth_suffix` from the board's
/// [`FabricationOutputSettings`]. If `settings.merge_drills` is true,
/// an additional merged file is written using `drills_merged_suffix`.
///
/// File names are formed as `{board.name}{suffix}`.
pub fn export_all_drills(
    board: &Board,
    library: &dyn BoardLibrary,
    output_dir: &Path,
    settings: &FabricationOutputSettings,
) -> Result<DrillSummary, String> {
    std::fs::create_dir_all(output_dir)
        .map_err(|e| format!("failed to create output directory: {e}"))?;

    // ── PTH ────────────────────────────────────────────────────────────
    let pth_hits = collect_pth_hits(board, library)?;
    let pth_content = build_writer(&pth_hits).to_string();
    let pth_path = output_dir.join(format!("{}{}", board.name, settings.drills_pth_suffix));
    std::fs::write(&pth_path, &pth_content)
        .map_err(|e| format!("failed to write PTH drill file: {e}"))?;

    // ── NPTH ────────────────────────────────────────────────────────────
    let npth_hits = collect_npth_hits(board);
    let npth_content = build_writer(&npth_hits).to_string();
    let npth_path = output_dir.join(format!("{}{}", board.name, settings.drills_npth_suffix));
    std::fs::write(&npth_path, &npth_content)
        .map_err(|e| format!("failed to write NPTH drill file: {e}"))?;

    let mut files = vec![
        DrillFile {
            path: pth_path,
            kind: DrillFileKind::Pth,
            hole_count: pth_hits.len(),
        },
        DrillFile {
            path: npth_path,
            kind: DrillFileKind::Npth,
            hole_count: npth_hits.len(),
        },
    ];

    // ── Merged (optional) ───────────────────────────────────────────────
    if settings.merge_drills {
        let mut all_hits = pth_hits.clone();
        all_hits.extend(npth_hits.clone());
        let merged_content = build_writer(&all_hits).to_string();
        let merged_path =
            output_dir.join(format!("{}{}", board.name, settings.drills_merged_suffix));
        std::fs::write(&merged_path, &merged_content)
            .map_err(|e| format!("failed to write merged drill file: {e}"))?;
        files.push(DrillFile {
            path: merged_path,
            kind: DrillFileKind::Merged,
            hole_count: all_hits.len(),
        });
    }

    Ok(DrillSummary {
        files,
        pth_hole_count: pth_hits.len(),
        npth_hole_count: npth_hits.len(),
    })
}

// ═══════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    use uuid::Uuid;

    use volt_core::common::*;
    use volt_core::library::{
        Device, Footprint, FootprintPad, LibraryMeta, Package, PackagePad, PadHole,
    };
    use volt_core::project::*;

    use crate::gerber::MapBoardLibrary;

    // ── Helpers ──────────────────────────────────────────────────────────

    fn default_design_rules() -> DesignRules {
        serde_json::from_str("{}").unwrap()
    }
    fn default_drc_settings() -> DrcSettings {
        serde_json::from_str("{}").unwrap()
    }
    fn default_grid() -> Grid {
        Grid {
            interval: 2.54,
            unit: GridUnit::Millimeters,
        }
    }

    fn empty_board(name: &str) -> Board {
        Board {
            uuid: Uuid::new_v4(),
            name: name.into(),
            grid: default_grid(),
            inner_layers: 0,
            thickness: 1.6,
            solder_resist: SolderResistColor::Green,
            silkscreen: SilkscreenColor::White,
            default_font: "newstroke.bene".to_string(),
            design_rules: default_design_rules(),
            drc_settings: default_drc_settings(),
            fabrication_output_settings: FabricationOutputSettings::default(),
            devices: vec![],
            net_segments: vec![],
            planes: vec![],
            polygons: vec![],
            holes: vec![],
        }
    }

    fn make_via(drill: f64, x: f64, y: f64) -> Via {
        Via {
            uuid: Uuid::new_v4(),
            from_layer: Layer::TopCopper,
            to_layer: Layer::BottomCopper,
            position: Position::new(x, y),
            drill,
            size: ViaSize::Auto,
            exposure: ViaExposure::Auto,
        }
    }

    fn make_hole(diameter: f64, x: f64, y: f64) -> BoardHole {
        BoardHole {
            uuid: Uuid::new_v4(),
            diameter,
            stop_mask: StopMaskConfig::Auto,
            lock: false,
            path: vec![Vertex {
                position: Position::new(x, y),
                angle: Angle(0.0),
            }],
        }
    }

    // ── ExcellonWriter unit tests ────────────────────────────────────────

    #[test]
    fn coord_formatting_microns() {
        assert_eq!(format_coord(0.0), "0");
        assert_eq!(format_coord(1.0), "1000");
        assert_eq!(format_coord(12.0), "12000");
        assert_eq!(format_coord(12.345), "12345");
        assert_eq!(format_coord(-5.0), "-5000");
        assert_eq!(format_coord(0.001), "1");
    }

    #[test]
    fn writer_header_and_footer() {
        let mut w = ExcellonWriter::new();
        w.add_tool(0.3);
        let s = w.to_string();
        assert!(s.starts_with("M48\n"), "should start with M48 header: {s}");
        assert!(s.contains("METRIC,TZ\n"));
        assert!(s.contains("T1C0.300\n"));
        assert!(s.contains("%\n"));
        assert!(s.trim_end().ends_with("M30"), "should end with M30: {s}");
    }

    #[test]
    fn writer_hits_use_selected_tool() {
        let mut w = ExcellonWriter::new();
        let t1 = w.add_tool(0.3);
        let t2 = w.add_tool(0.8);
        assert_eq!(t1, 1);
        assert_eq!(t2, 2);
        w.add_hit(t1, 12.0, 15.0);
        w.add_hit(t2, 5.0, 5.0);
        w.add_hit(t1, 28.0, 15.0);

        let s = w.to_string();
        // Tool selections appear
        assert!(s.contains("\nT1\n"));
        assert!(s.contains("\nT2\n"));
        // Hits are grouped by tool
        assert!(s.contains("X12000Y15000\n"));
        assert!(s.contains("X28000Y15000\n"));
        assert!(s.contains("X5000Y5000\n"));
    }

    #[test]
    fn find_or_add_tool_dedups_same_diameter() {
        let mut w = ExcellonWriter::new();
        let a = w.find_or_add_tool(0.3);
        let b = w.find_or_add_tool(0.3);
        let c = w.find_or_add_tool(0.3005); // within 0.001 mm
        let d = w.find_or_add_tool(0.8);
        assert_eq!(a, 1);
        assert_eq!(b, 1);
        assert_eq!(c, 1, "diameters within tolerance should reuse tool");
        assert_eq!(d, 2);
        assert_eq!(w.tool_count(), 2);
    }

    #[test]
    fn find_or_add_tool_rejects_different_diameter() {
        let mut w = ExcellonWriter::new();
        w.find_or_add_tool(0.3);
        let other = w.find_or_add_tool(0.35);
        assert_eq!(other, 2);
    }

    // ── PTH export ───────────────────────────────────────────────────────

    #[test]
    fn pth_drills_from_vias() {
        let mut board = empty_board("pth_test");
        board.net_segments.push(BoardNetSegment {
            uuid: Uuid::new_v4(),
            net: None,
            traces: vec![],
            vias: vec![
                make_via(0.3, 10.0, 20.0),
                make_via(0.8, 30.0, 40.0),
                make_via(0.3, 50.0, 60.0),
            ],
            junctions: vec![],
            pads: vec![],
        });

        let library = MapBoardLibrary::new();
        let content = export_pth_drills(&board, &library).unwrap();

        // Header
        assert!(content.contains("M48"));
        assert!(content.contains("METRIC,TZ"));

        // Tool definitions: sorted ascending → T1=0.3, T2=0.8
        assert!(content.contains("T1C0.300"));
        assert!(content.contains("T2C0.800"));

        // Hit coordinates, in microns
        assert!(content.contains("X10000Y20000"));
        assert!(content.contains("X30000Y40000"));
        assert!(content.contains("X50000Y60000"));

        // End-of-file
        assert!(content.trim_end().ends_with("M30"));
    }

    #[test]
    fn pth_drills_include_tht_pad_holes() {
        // Build a tiny library: one package with a footprint that has
        // one THT pad with a 1.0 mm drill hole at the pad centre.
        let pkg_uuid = Uuid::new_v4();
        let fp_uuid = Uuid::new_v4();
        let pad_uuid = Uuid::new_v4();
        let pkg_pad_uuid = Uuid::new_v4();
        let dev_uuid = Uuid::new_v4();

        let meta = |uuid: Uuid, name: &str| LibraryMeta {
            uuid,
            name: name.into(),
            description: String::new(),
            keywords: String::new(),
            author: String::new(),
            version: "v1".into(),
            created: chrono::Utc::now(),
            deprecated: false,
            category: None,
        };

        let package = Package {
            meta: meta(pkg_uuid, "pkg"),
            assembly_type: AssemblyType::Tht,
            grid_interval: 2.54,
            min_copper_clearance: 0.2,
            pads: vec![PackagePad {
                uuid: pkg_pad_uuid,
                name: "1".into(),
            }],
            footprints: vec![Footprint {
                uuid: fp_uuid,
                name: "default".into(),
                description: String::new(),
                model_position: Default::default(),
                model_rotation: Default::default(),
                pads: vec![FootprintPad {
                    uuid: pad_uuid,
                    package_pad: pkg_pad_uuid,
                    side: PadSide::ThroughHole,
                    shape: PadShape::Round,
                    position: Position::new(0.0, 0.0),
                    rotation: Angle(0.0),
                    width: 1.8,
                    height: 1.8,
                    radius: 0.0,
                    stop_mask: StopMaskConfig::Auto,
                    solder_paste: SolderPasteConfig::Off,
                    clearance: 0.0,
                    function: PadFunction::Standard,
                    holes: vec![PadHole {
                        uuid: Uuid::new_v4(),
                        diameter: 1.0,
                        path: vec![],
                    }],
                }],
                polygons: vec![],
                texts: vec![],
            }],
        };

        let device = Device {
            meta: meta(dev_uuid, "dev"),
            component: Uuid::new_v4(),
            package: pkg_uuid,
            pad_mappings: vec![],
            parts: vec![],
        };

        let mut devices = HashMap::new();
        devices.insert(dev_uuid, device);
        let mut packages = HashMap::new();
        packages.insert(pkg_uuid, package);
        let library = MapBoardLibrary { devices, packages };

        let mut board = empty_board("tht_test");
        board.devices.push(BoardDevice {
            component: Uuid::new_v4(),
            lib_device: dev_uuid,
            lib_footprint: fp_uuid,
            position: Position::new(25.0, 30.0),
            rotation: Angle(0.0),
            flip: false,
            lock: false,
            texts: vec![],
        });

        let content = export_pth_drills(&board, &library).unwrap();

        // One tool (1.000 mm) + hit at board position (25, 30)
        assert!(content.contains("T1C1.000"));
        assert!(content.contains("X25000Y30000"));
    }

    // ── NPTH export ──────────────────────────────────────────────────────

    #[test]
    fn npth_drills_from_mounting_holes() {
        let mut board = empty_board("npth_test");
        board.holes.push(make_hole(3.2, 5.0, 5.0));
        board.holes.push(make_hole(3.2, 95.0, 5.0));
        board.holes.push(make_hole(3.2, 5.0, 75.0));
        board.holes.push(make_hole(3.2, 95.0, 75.0));

        let content = export_npth_drills(&board).unwrap();
        // Single tool (3.2 mm) with 4 hits at the corners.
        assert!(content.contains("T1C3.200"));
        assert!(content.contains("X5000Y5000"));
        assert!(content.contains("X95000Y5000"));
        assert!(content.contains("X5000Y75000"));
        assert!(content.contains("X95000Y75000"));
        assert!(content.trim_end().ends_with("M30"));
    }

    #[test]
    fn npth_drills_empty_board_still_valid() {
        let board = empty_board("empty");
        let content = export_npth_drills(&board).unwrap();
        // Even without holes, the file must be syntactically valid.
        assert!(content.starts_with("M48"));
        assert!(content.trim_end().ends_with("M30"));
        // No tool definitions.
        assert!(!content.contains("T1C"));
    }

    // ── Tool dedup end-to-end ────────────────────────────────────────────

    #[test]
    fn tool_dedup_across_hits() {
        let mut board = empty_board("dedup");
        board.net_segments.push(BoardNetSegment {
            uuid: Uuid::new_v4(),
            net: None,
            traces: vec![],
            vias: vec![
                make_via(0.3, 1.0, 1.0),
                make_via(0.3, 2.0, 2.0),
                make_via(0.3, 3.0, 3.0),
            ],
            junctions: vec![],
            pads: vec![],
        });
        let library = MapBoardLibrary::new();
        let content = export_pth_drills(&board, &library).unwrap();

        // Exactly one tool definition.
        let tool_def_count = content.matches("T1C").count();
        assert_eq!(tool_def_count, 1, "expected single tool def: {content}");
        assert!(!content.contains("T2C"));
    }

    // ── File orchestration ──────────────────────────────────────────────

    #[test]
    fn export_all_drills_writes_both_files() {
        let tmp = std::env::temp_dir().join(format!(
            "volt_excellon_test_{}",
            Uuid::new_v4().simple()
        ));
        let mut board = empty_board("myboard");
        board.net_segments.push(BoardNetSegment {
            uuid: Uuid::new_v4(),
            net: None,
            traces: vec![],
            vias: vec![make_via(0.3, 10.0, 10.0)],
            junctions: vec![],
            pads: vec![],
        });
        board.holes.push(make_hole(3.2, 5.0, 5.0));

        let library = MapBoardLibrary::new();
        let settings = FabricationOutputSettings::default();
        let summary =
            export_all_drills(&board, &library, &tmp, &settings).expect("export ok");

        assert_eq!(summary.pth_hole_count, 1);
        assert_eq!(summary.npth_hole_count, 1);
        assert_eq!(summary.files.len(), 2);

        // Both files exist and have valid content.
        for f in &summary.files {
            let content = std::fs::read_to_string(&f.path).expect("read");
            assert!(content.starts_with("M48"));
            assert!(content.trim_end().ends_with("M30"));
        }

        // Merged disabled by default.
        assert!(!summary
            .files
            .iter()
            .any(|f| f.kind == DrillFileKind::Merged));

        // Clean up
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn export_all_drills_with_merge() {
        let tmp = std::env::temp_dir().join(format!(
            "volt_excellon_merge_{}",
            Uuid::new_v4().simple()
        ));
        let mut board = empty_board("merged");
        board.net_segments.push(BoardNetSegment {
            uuid: Uuid::new_v4(),
            net: None,
            traces: vec![],
            vias: vec![make_via(0.3, 10.0, 10.0)],
            junctions: vec![],
            pads: vec![],
        });
        board.holes.push(make_hole(3.2, 5.0, 5.0));

        let library = MapBoardLibrary::new();
        let mut settings = FabricationOutputSettings::default();
        settings.merge_drills = true;

        let summary =
            export_all_drills(&board, &library, &tmp, &settings).expect("export ok");
        assert_eq!(summary.files.len(), 3);
        let merged = summary
            .files
            .iter()
            .find(|f| f.kind == DrillFileKind::Merged)
            .expect("merged file present");
        assert_eq!(merged.hole_count, 2);

        let content = std::fs::read_to_string(&merged.path).unwrap();
        // Merged file has both hits; tools sorted ascending → 0.3, 3.2.
        assert!(content.contains("T1C0.300"));
        assert!(content.contains("T2C3.200"));
        assert!(content.contains("X10000Y10000"));
        assert!(content.contains("X5000Y5000"));

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
