//! Gerber RS-274X export for Volt PCB boards.
//!
//! Generates industry-standard Gerber files for PCB fabrication, including
//! copper layers, soldermask, silkscreen, and board outline.

use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};

use uuid::Uuid;

use volt_core::common::*;
use volt_core::library::{Device, FootprintPad, Package};
use volt_core::project::*;

// ═══════════════════════════════════════════════════════════════════════════
// Error types
// ═══════════════════════════════════════════════════════════════════════════

/// Errors that can occur during Gerber export.
#[derive(Debug, thiserror::Error)]
pub enum GerberError {
    #[error("board device not found for component {0}")]
    MissingDevice(Uuid),
    #[error("package not found: {0}")]
    MissingPackage(Uuid),
    #[error("footprint not found: {0}")]
    MissingFootprint(Uuid),
    #[error("footprint pad not found: {0}")]
    MissingPad(Uuid),
    #[error("via not found: {0}")]
    MissingVia(Uuid),
    #[error("junction not found: {0}")]
    MissingJunction(Uuid),
    #[error("no board outline polygon found")]
    NoBoardOutline,
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
}

/// Result type alias for Gerber operations.
pub type Result<T> = std::result::Result<T, GerberError>;

// ═══════════════════════════════════════════════════════════════════════════
// Aperture
// ═══════════════════════════════════════════════════════════════════════════

/// A Gerber aperture definition.
#[derive(Debug, Clone)]
pub enum Aperture {
    Circle { diameter: f64 },
    Rectangle { width: f64, height: f64 },
}

// ═══════════════════════════════════════════════════════════════════════════
// GerberWriter — low-level RS-274X writer
// ═══════════════════════════════════════════════════════════════════════════

/// Low-level Gerber RS-274X format writer.
///
/// Accumulates Gerber commands into an internal buffer. Coordinates are
/// specified in millimeters and converted to the Gerber integer format
/// using the configured coordinate format (default: 4.6).
pub struct GerberWriter {
    buf: String,
    /// Number of integer digits in coordinate format.
    #[allow(dead_code)]
    int_digits: u8,
    /// Number of decimal digits in coordinate format.
    dec_digits: u8,
    apertures: Vec<Aperture>,
    current_aperture: Option<usize>,
}

impl GerberWriter {
    /// Create a new writer with the standard RS-274X header.
    ///
    /// Emits: format spec (4.6), millimetre units, positive image polarity.
    pub fn new() -> Self {
        let now = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ");
        let mut buf = String::with_capacity(4096);
        buf.push_str(&format!("G04 Generated by Volt EDA on {}*\n", now));
        buf.push_str("%FSLAX46Y46*%\n");
        buf.push_str("%MOMM*%\n");
        buf.push_str("%IPPOS*%\n");
        Self {
            buf,
            int_digits: 4,
            dec_digits: 6,
            apertures: Vec::new(),
            current_aperture: None,
        }
    }

    /// Create a new writer with Gerber X2 attributes in the header.
    ///
    /// Adds %TF.GenerationSoftware, %TF.CreationDate, %TF.FileFunction,
    /// %TF.FilePolarity, and %TF.Part attributes per Ucamco spec.
    pub fn new_x2(file_function: &str, file_polarity: &str) -> Self {
        let now = chrono::Utc::now();
        let date_str = now.format("%Y-%m-%dT%H:%M:%SZ");
        let mut buf = String::with_capacity(4096);
        buf.push_str(&format!("G04 Generated by Volt EDA on {}*\n", date_str));
        buf.push_str("%TF.GenerationSoftware,Volt,volt-eda,0.1*%\n");
        buf.push_str(&format!("%TF.CreationDate,{}*%\n", date_str));
        buf.push_str(&format!("%TF.FileFunction,{}*%\n", file_function));
        buf.push_str(&format!("%TF.FilePolarity,{}*%\n", file_polarity));
        buf.push_str("%TF.Part,Single*%\n");
        buf.push_str("%FSLAX46Y46*%\n");
        buf.push_str("%MOMM*%\n");
        buf.push_str("%IPPOS*%\n");
        Self {
            buf,
            int_digits: 4,
            dec_digits: 6,
            apertures: Vec::new(),
            current_aperture: None,
        }
    }

    /// Register an aperture. Returns its index (used with [`select_aperture`]).
    ///
    /// D-codes start at D10. The aperture definition is emitted immediately.
    pub fn add_aperture(&mut self, aperture: Aperture) -> usize {
        let index = self.apertures.len();
        let d_code = index + 10;
        match &aperture {
            Aperture::Circle { diameter } => {
                self.buf
                    .push_str(&format!("%ADD{}C,{:.6}*%\n", d_code, diameter));
            }
            Aperture::Rectangle { width, height } => {
                self.buf
                    .push_str(&format!("%ADD{}R,{:.6}X{:.6}*%\n", d_code, width, height));
            }
        }
        self.apertures.push(aperture);
        index
    }

    /// Select an aperture by index. Emits `D{code}*` only if different
    /// from the currently selected aperture.
    pub fn select_aperture(&mut self, index: usize) {
        if self.current_aperture != Some(index) {
            let d_code = index + 10;
            self.buf.push_str(&format!("D{}*\n", d_code));
            self.current_aperture = Some(index);
        }
    }

    /// Move to position without drawing (D02).
    pub fn move_to(&mut self, x: f64, y: f64) {
        let cx = self.format_coord(x);
        let cy = self.format_coord(y);
        self.buf.push_str(&format!("X{}Y{}D02*\n", cx, cy));
    }

    /// Draw a line to position (D01).
    pub fn line_to(&mut self, x: f64, y: f64) {
        let cx = self.format_coord(x);
        let cy = self.format_coord(y);
        self.buf.push_str(&format!("X{}Y{}D01*\n", cx, cy));
    }

    /// Flash the current aperture at position (D03).
    pub fn flash(&mut self, x: f64, y: f64) {
        let cx = self.format_coord(x);
        let cy = self.format_coord(y);
        self.buf.push_str(&format!("X{}Y{}D03*\n", cx, cy));
    }

    /// Set layer polarity to dark (`%LPD*%`).
    pub fn set_polarity_dark(&mut self) {
        self.buf.push_str("%LPD*%\n");
    }

    /// Set layer polarity to clear (`%LPC*%`).
    pub fn set_polarity_clear(&mut self) {
        self.buf.push_str("%LPC*%\n");
    }

    /// Begin a filled region (`G36*`).
    pub fn region_start(&mut self) {
        self.buf.push_str("G36*\n");
    }

    /// End a filled region (`G37*`).
    pub fn region_end(&mut self) {
        self.buf.push_str("G37*\n");
    }

    /// Emit an end-of-file command (`M02*`).
    pub fn finish(&mut self) {
        self.buf.push_str("M02*\n");
    }

    /// Add a comment line (`G04`).
    pub fn comment(&mut self, text: &str) {
        self.buf.push_str(&format!("G04 {}*\n", text));
    }

    /// Convert a millimetre value to a Gerber coordinate string.
    ///
    /// Multiplies by 10^dec_digits and rounds to the nearest integer.
    fn format_coord(&self, mm: f64) -> String {
        let scale = 10f64.powi(self.dec_digits as i32);
        let value = (mm * scale).round() as i64;
        format!("{}", value)
    }
}

impl fmt::Display for GerberWriter {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.buf)
    }
}

impl Default for GerberWriter {
    fn default() -> Self {
        Self::new()
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// BoardLibrary trait
// ═══════════════════════════════════════════════════════════════════════════

/// Provides access to library elements needed for board export.
pub trait BoardLibrary {
    fn get_device(&self, uuid: &Uuid) -> Option<&Device>;
    fn get_package(&self, uuid: &Uuid) -> Option<&Package>;
}

/// A simple hash-map-backed [`BoardLibrary`] implementation.
#[derive(Debug, Default)]
pub struct MapBoardLibrary {
    pub devices: HashMap<Uuid, Device>,
    pub packages: HashMap<Uuid, Package>,
}

impl MapBoardLibrary {
    pub fn new() -> Self {
        Self::default()
    }
}

impl BoardLibrary for MapBoardLibrary {
    fn get_device(&self, uuid: &Uuid) -> Option<&Device> {
        self.devices.get(uuid)
    }

    fn get_package(&self, uuid: &Uuid) -> Option<&Package> {
        self.packages.get(uuid)
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Geometry helpers
// ═══════════════════════════════════════════════════════════════════════════

/// Transform a point from footprint-local coordinates to board coordinates,
/// applying device flip, rotation, and translation.
pub fn transform_point(px: f64, py: f64, device: &BoardDevice) -> (f64, f64) {
    let mut x = px;
    let y = py;
    // Mirror X when flipped to the bottom side.
    if device.flip {
        x = -x;
    }
    let angle = device.rotation.0.to_radians();
    let cos = angle.cos();
    let sin = angle.sin();
    let rx = x * cos - y * sin;
    let ry = x * sin + y * cos;
    (rx + device.position.x, ry + device.position.y)
}

/// Determine the effective pad side after accounting for device flip.
fn effective_pad_side(pad_side: PadSide, flipped: bool) -> PadSide {
    if !flipped {
        return pad_side;
    }
    match pad_side {
        PadSide::Top => PadSide::Bottom,
        PadSide::Bottom => PadSide::Top,
        PadSide::ThroughHole => PadSide::ThroughHole,
    }
}

/// Check whether a pad should appear on a given copper layer.
fn pad_on_copper_layer(pad_side: PadSide, flipped: bool, layer: Layer) -> bool {
    let side = effective_pad_side(pad_side, flipped);
    matches!(
        (side, layer),
        (PadSide::Top, Layer::TopCopper)
            | (PadSide::Bottom, Layer::BottomCopper)
            | (PadSide::ThroughHole, Layer::TopCopper)
            | (PadSide::ThroughHole, Layer::BottomCopper)
            | (PadSide::ThroughHole, Layer::InnerCopper(_))
    )
}

/// Check whether a pad should have a soldermask opening on a given side.
fn pad_on_soldermask(pad_side: PadSide, flipped: bool, top: bool) -> bool {
    let side = effective_pad_side(pad_side, flipped);
    matches!(
        (side, top),
        (PadSide::Top, true) | (PadSide::Bottom, false) | (PadSide::ThroughHole, _)
    )
}

/// Return an ordinal number for a copper layer (for range checks on vias).
fn layer_ordinal(layer: Layer) -> Option<i32> {
    match layer {
        Layer::TopCopper => Some(0),
        Layer::InnerCopper(n) => Some(n as i32),
        Layer::BottomCopper => Some(1000),
        _ => None,
    }
}

/// Check whether a via is present on a given copper layer.
fn via_on_layer(via: &Via, layer: Layer) -> bool {
    let lo = layer_ordinal(layer);
    let from = layer_ordinal(via.from_layer);
    let to = layer_ordinal(via.to_layer);
    match (lo, from, to) {
        (Some(l), Some(f), Some(t)) => {
            let (min, max) = if f <= t { (f, t) } else { (t, f) };
            l >= min && l <= max
        }
        _ => false,
    }
}

/// Compute the outer (copper ring) diameter of a via.
fn compute_via_diameter(via: &Via, rules: &DesignRules) -> f64 {
    match via.size {
        ViaSize::Manual(d) => d,
        ViaSize::Auto => {
            let ring = (rules.via_annular_ring_ratio * via.drill)
                .max(rules.via_annular_ring_min)
                .min(rules.via_annular_ring_max);
            via.drill + 2.0 * ring
        }
    }
}

/// Compute the soldermask clearance for a footprint pad, or `None` if the
/// pad has no mask opening.
fn stopmask_clearance_fp(
    pad: &volt_core::library::FootprintPad,
    rules: &DesignRules,
) -> Option<f64> {
    match pad.stop_mask {
        StopMaskConfig::Off => None,
        StopMaskConfig::Manual(c) => Some(c),
        StopMaskConfig::Auto => {
            let max_dim = pad.width.max(pad.height);
            let clearance = (rules.stopmask_clearance_ratio * max_dim)
                .max(rules.stopmask_clearance_min)
                .min(rules.stopmask_clearance_max);
            Some(clearance)
        }
    }
}

/// Compute the soldermask clearance for a standalone board pad, or `None`.
fn stopmask_clearance_board_pad(pad: &BoardPad, rules: &DesignRules) -> Option<f64> {
    match pad.stop_mask {
        StopMaskConfig::Off => None,
        StopMaskConfig::Manual(c) => Some(c),
        StopMaskConfig::Auto => {
            let max_dim = pad.size_width.max(pad.size_height);
            let clearance = (rules.stopmask_clearance_ratio * max_dim)
                .max(rules.stopmask_clearance_min)
                .min(rules.stopmask_clearance_max);
            Some(clearance)
        }
    }
}

/// Return the soldermask exposure clearance for a via, or `None` if tented.
fn via_exposure_clearance(via: &Via, drc: &DrcSettings) -> Option<f64> {
    match via.exposure {
        ViaExposure::Off => None,
        ViaExposure::Manual(clearance) => Some(clearance),
        ViaExposure::Auto => {
            if via.drill <= drc.max_tented_via_drill_diameter {
                None // tented — no mask opening
            } else {
                Some(0.1) // default small clearance for exposed vias
            }
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Aperture cache — deduplicates aperture definitions
// ═══════════════════════════════════════════════════════════════════════════

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
enum ApertureKey {
    Circle { diameter_nm: i64 },
    Rectangle { width_nm: i64, height_nm: i64 },
}

fn mm_to_nm(mm: f64) -> i64 {
    (mm * 1_000_000.0).round() as i64
}

struct ApertureCache {
    map: HashMap<ApertureKey, usize>,
}

impl ApertureCache {
    fn new() -> Self {
        Self {
            map: HashMap::new(),
        }
    }

    fn circle(&mut self, writer: &mut GerberWriter, diameter: f64) -> usize {
        let key = ApertureKey::Circle {
            diameter_nm: mm_to_nm(diameter),
        };
        if let Some(&idx) = self.map.get(&key) {
            return idx;
        }
        let idx = writer.add_aperture(Aperture::Circle { diameter });
        self.map.insert(key, idx);
        idx
    }

    fn rectangle(&mut self, writer: &mut GerberWriter, width: f64, height: f64) -> usize {
        let key = ApertureKey::Rectangle {
            width_nm: mm_to_nm(width),
            height_nm: mm_to_nm(height),
        };
        if let Some(&idx) = self.map.get(&key) {
            return idx;
        }
        let idx = writer.add_aperture(Aperture::Rectangle { width, height });
        self.map.insert(key, idx);
        idx
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Board geometry lookup maps
// ═══════════════════════════════════════════════════════════════════════════

/// Pre-computed lookup maps for resolving trace endpoints.
struct BoardMaps<'a> {
    via_map: HashMap<Uuid, &'a Via>,
    junction_map: HashMap<Uuid, Position>,
    /// ComponentInstance UUID → BoardDevice
    device_map: HashMap<Uuid, &'a BoardDevice>,
}

impl<'a> BoardMaps<'a> {
    fn build(board: &'a Board) -> Self {
        let mut via_map = HashMap::new();
        let mut junction_map = HashMap::new();
        for seg in &board.net_segments {
            for via in &seg.vias {
                via_map.insert(via.uuid, via);
            }
            for junc in &seg.junctions {
                junction_map.insert(junc.uuid, junc.position);
            }
        }
        let mut device_map = HashMap::new();
        for dev in &board.devices {
            device_map.insert(dev.component, dev);
        }
        Self {
            via_map,
            junction_map,
            device_map,
        }
    }

    /// Resolve a trace endpoint to board-space (x, y) coordinates.
    fn resolve_endpoint(
        &self,
        endpoint: &TraceEndpoint,
        library: &dyn BoardLibrary,
    ) -> Result<(f64, f64)> {
        match endpoint {
            TraceEndpoint::Via { via } => {
                let v = self.via_map.get(via).ok_or(GerberError::MissingVia(*via))?;
                Ok((v.position.x, v.position.y))
            }
            TraceEndpoint::Junction { junction } => {
                let pos = self
                    .junction_map
                    .get(junction)
                    .ok_or(GerberError::MissingJunction(*junction))?;
                Ok((pos.x, pos.y))
            }
            TraceEndpoint::Device { device, pad } => {
                let board_dev = self
                    .device_map
                    .get(device)
                    .ok_or(GerberError::MissingDevice(*device))?;
                let lib_dev = library
                    .get_device(&board_dev.lib_device)
                    .ok_or(GerberError::MissingDevice(board_dev.lib_device))?;
                let pkg = library
                    .get_package(&lib_dev.package)
                    .ok_or(GerberError::MissingPackage(lib_dev.package))?;
                let footprint = pkg
                    .footprints
                    .iter()
                    .find(|f| f.uuid == board_dev.lib_footprint)
                    .ok_or(GerberError::MissingFootprint(board_dev.lib_footprint))?;
                let fp_pad = footprint
                    .pads
                    .iter()
                    .find(|p| p.uuid == *pad || p.package_pad == *pad)
                    .ok_or(GerberError::MissingPad(*pad))?;
                Ok(transform_point(
                    fp_pad.position.x,
                    fp_pad.position.y,
                    board_dev,
                ))
            }
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Copper layer export
// ═══════════════════════════════════════════════════════════════════════════

/// Export a single copper layer as a Gerber RS-274X string.
///
/// Includes traces, device pads, standalone pads, vias, and copper planes.
pub fn export_copper_layer(
    board: &Board,
    _circuit: &Circuit,
    library: &dyn BoardLibrary,
    layer: Layer,
) -> Result<String> {
    let file_function = match layer {
        Layer::TopCopper => "Copper,L1,Top".to_string(),
        Layer::BottomCopper => "Copper,L2,Bot".to_string(),
        Layer::InnerCopper(n) => format!("Copper,L{},Inr", n + 1),
        _ => "Copper,L1,Top".to_string(),
    };
    let mut writer = GerberWriter::new_x2(&file_function, "Positive");
    let mut cache = ApertureCache::new();
    let maps = BoardMaps::build(board);

    writer.comment(&format!("Layer: {:?}", layer));

    // ── Collect geometry ─────────────────────────────────────────────────

    // Traces
    let mut trace_draws: Vec<(usize, (f64, f64), (f64, f64))> = Vec::new();
    for seg in &board.net_segments {
        for trace in &seg.traces {
            if trace.layer != layer {
                continue;
            }
            let from = maps.resolve_endpoint(&trace.from, library)?;
            let to = maps.resolve_endpoint(&trace.to, library)?;
            let ap = cache.circle(&mut writer, trace.width);
            trace_draws.push((ap, from, to));
        }
    }

    // Device footprint pads
    let mut pad_flashes: Vec<(usize, f64, f64)> = Vec::new();
    for dev in &board.devices {
        let Some(lib_dev) = library.get_device(&dev.lib_device) else {
            continue;
        };
        let Some(pkg) = library.get_package(&lib_dev.package) else {
            continue;
        };
        let Some(footprint) = pkg.footprints.iter().find(|f| f.uuid == dev.lib_footprint) else {
            continue;
        };
        for fp_pad in &footprint.pads {
            if !pad_on_copper_layer(fp_pad.side, dev.flip, layer) {
                continue;
            }
            let (x, y) = transform_point(fp_pad.position.x, fp_pad.position.y, dev);
            let ap = match fp_pad.shape {
                PadShape::Round => cache.circle(&mut writer, fp_pad.width),
                _ => cache.rectangle(&mut writer, fp_pad.width, fp_pad.height),
            };
            pad_flashes.push((ap, x, y));
        }
    }

    // Standalone board pads
    for seg in &board.net_segments {
        for pad in &seg.pads {
            if !pad_on_copper_layer(pad.side, false, layer) {
                continue;
            }
            let ap = match pad.shape {
                PadShape::Round => cache.circle(&mut writer, pad.size_width),
                _ => cache.rectangle(&mut writer, pad.size_width, pad.size_height),
            };
            pad_flashes.push((ap, pad.position.x, pad.position.y));
        }
    }

    // Vias
    let mut via_flashes: Vec<(usize, f64, f64)> = Vec::new();
    for seg in &board.net_segments {
        for via in &seg.vias {
            if !via_on_layer(via, layer) {
                continue;
            }
            let diameter = compute_via_diameter(via, &board.design_rules);
            let ap = cache.circle(&mut writer, diameter);
            via_flashes.push((ap, via.position.x, via.position.y));
        }
    }

    // ── Draw ─────────────────────────────────────────────────────────────

    writer.set_polarity_dark();

    // Traces
    for (ap, from, to) in &trace_draws {
        writer.select_aperture(*ap);
        writer.move_to(from.0, from.1);
        writer.line_to(to.0, to.1);
    }

    // Pads
    for (ap, x, y) in &pad_flashes {
        writer.select_aperture(*ap);
        writer.flash(*x, *y);
    }

    // Vias
    for (ap, x, y) in &via_flashes {
        writer.select_aperture(*ap);
        writer.flash(*x, *y);
    }

    // Copper planes (filled regions from refill fragments)
    for plane in &board.planes {
        if plane.layer != layer {
            continue;
        }
        if !plane.fragments.is_empty() {
            // Use computed refill fragments
            for fragment in &plane.fragments {
                if fragment.contours.is_empty() {
                    continue;
                }
                // Outer boundary = dark region
                let outer = &fragment.contours[0];
                if outer.len() >= 3 {
                    writer.region_start();
                    writer.move_to(outer[0].x, outer[0].y);
                    for pt in &outer[1..] {
                        writer.line_to(pt.x, pt.y);
                    }
                    writer.line_to(outer[0].x, outer[0].y);
                    writer.region_end();
                }
                // Holes = clear regions
                for hole in &fragment.contours[1..] {
                    if hole.len() >= 3 {
                        writer.set_polarity_clear();
                        writer.region_start();
                        writer.move_to(hole[0].x, hole[0].y);
                        for pt in &hole[1..] {
                            writer.line_to(pt.x, pt.y);
                        }
                        writer.line_to(hole[0].x, hole[0].y);
                        writer.region_end();
                        writer.set_polarity_dark();
                    }
                }
            }
        } else if plane.vertices.len() >= 3 {
            // Fallback: raw plane outline (no refill computed)
            writer.region_start();
            let first = &plane.vertices[0];
            writer.move_to(first.position.x, first.position.y);
            for v in &plane.vertices[1..] {
                writer.line_to(v.position.x, v.position.y);
            }
            writer.line_to(first.position.x, first.position.y);
            writer.region_end();
        }
    }

    writer.finish();
    Ok(writer.to_string())
}

// ═══════════════════════════════════════════════════════════════════════════
// Soldermask layer export
// ═══════════════════════════════════════════════════════════════════════════

/// Export a soldermask layer (mask openings) as a Gerber RS-274X string.
///
/// Produces openings for pads (expanded by stopmask clearance) and for
/// exposed vias.
pub fn export_soldermask_layer(
    board: &Board,
    _circuit: &Circuit,
    library: &dyn BoardLibrary,
    top: bool,
) -> Result<String> {
    let file_function = if top {
        "Soldermask,Top"
    } else {
        "Soldermask,Bot"
    };
    let mut writer = GerberWriter::new_x2(file_function, "Negative");
    let mut cache = ApertureCache::new();
    let mut flashes: Vec<(usize, f64, f64)> = Vec::new();

    let side_name = if top { "Top" } else { "Bottom" };
    writer.comment(&format!("Soldermask {}", side_name));

    // Device footprint pads
    for dev in &board.devices {
        let Some(lib_dev) = library.get_device(&dev.lib_device) else {
            continue;
        };
        let Some(pkg) = library.get_package(&lib_dev.package) else {
            continue;
        };
        let Some(footprint) = pkg.footprints.iter().find(|f| f.uuid == dev.lib_footprint) else {
            continue;
        };
        for fp_pad in &footprint.pads {
            if !pad_on_soldermask(fp_pad.side, dev.flip, top) {
                continue;
            }
            let Some(clearance) = stopmask_clearance_fp(fp_pad, &board.design_rules) else {
                continue;
            };
            let (x, y) = transform_point(fp_pad.position.x, fp_pad.position.y, dev);
            let w = fp_pad.width + 2.0 * clearance;
            let h = fp_pad.height + 2.0 * clearance;
            let ap = match fp_pad.shape {
                PadShape::Round => cache.circle(&mut writer, w),
                _ => cache.rectangle(&mut writer, w, h),
            };
            flashes.push((ap, x, y));
        }
    }

    // Standalone board pads
    for seg in &board.net_segments {
        for pad in &seg.pads {
            if !pad_on_soldermask(pad.side, false, top) {
                continue;
            }
            let Some(clearance) = stopmask_clearance_board_pad(pad, &board.design_rules) else {
                continue;
            };
            let w = pad.size_width + 2.0 * clearance;
            let h = pad.size_height + 2.0 * clearance;
            let ap = match pad.shape {
                PadShape::Round => cache.circle(&mut writer, w),
                _ => cache.rectangle(&mut writer, w, h),
            };
            flashes.push((ap, pad.position.x, pad.position.y));
        }
    }

    // Via mask openings (only if exposed / not tented)
    for seg in &board.net_segments {
        for via in &seg.vias {
            // Check if the via reaches this soldermask side.
            let reaches = if top {
                via.from_layer == Layer::TopCopper || via.to_layer == Layer::TopCopper
            } else {
                via.from_layer == Layer::BottomCopper || via.to_layer == Layer::BottomCopper
            };
            if !reaches {
                continue;
            }
            let Some(clearance) = via_exposure_clearance(via, &board.drc_settings) else {
                continue;
            };
            let via_diameter = compute_via_diameter(via, &board.design_rules);
            let opening = via_diameter + 2.0 * clearance;
            let ap = cache.circle(&mut writer, opening);
            flashes.push((ap, via.position.x, via.position.y));
        }
    }

    // Draw all mask openings
    writer.set_polarity_dark();
    for (ap, x, y) in &flashes {
        writer.select_aperture(*ap);
        writer.flash(*x, *y);
    }

    writer.finish();
    Ok(writer.to_string())
}

// ═══════════════════════════════════════════════════════════════════════════
// Solder paste (stencil) layer export
// ═══════════════════════════════════════════════════════════════════════════

/// Export a solder-paste (stencil) layer as a Gerber RS-274X string.
///
/// Produces apertures for SMD pads only (no THT, no vias).
/// Aperture size is the pad size shrunk by the paste clearance.
pub fn export_paste_layer(
    board: &Board,
    _circuit: &Circuit,
    library: &dyn BoardLibrary,
    top: bool,
) -> Result<String> {
    let file_function = if top { "Paste,Top" } else { "Paste,Bot" };
    let mut writer = GerberWriter::new_x2(file_function, "Positive");
    let mut cache = ApertureCache::new();
    let mut flashes: Vec<(usize, f64, f64)> = Vec::new();

    let side_name = if top { "Top" } else { "Bottom" };
    writer.comment(&format!("Solder Paste {}", side_name));

    let rules = &board.design_rules;

    // Device footprint pads (SMD only)
    for dev in &board.devices {
        let Some(lib_dev) = library.get_device(&dev.lib_device) else {
            continue;
        };
        let Some(pkg) = library.get_package(&lib_dev.package) else {
            continue;
        };
        let Some(footprint) = pkg.footprints.iter().find(|f| f.uuid == dev.lib_footprint) else {
            continue;
        };
        for fp_pad in &footprint.pads {
            // Only SMD pads get paste — skip THT
            if fp_pad.side == PadSide::ThroughHole {
                continue;
            }
            if !pad_on_paste_side(fp_pad.side, dev.flip, top) {
                continue;
            }
            let shrink = match fp_pad.solder_paste {
                SolderPasteConfig::Auto => paste_shrink_auto(fp_pad, rules),
                SolderPasteConfig::Manual(v) => v,
                SolderPasteConfig::Off => continue,
            };
            let (x, y) = transform_point(fp_pad.position.x, fp_pad.position.y, dev);
            let w = (fp_pad.width - 2.0 * shrink).max(0.01);
            let h = (fp_pad.height - 2.0 * shrink).max(0.01);
            let ap = match fp_pad.shape {
                PadShape::Round => cache.circle(&mut writer, w),
                _ => cache.rectangle(&mut writer, w, h),
            };
            flashes.push((ap, x, y));
        }
    }

    // Standalone board pads (SMD only)
    for seg in &board.net_segments {
        for pad in &seg.pads {
            if pad.side == PadSide::ThroughHole {
                continue;
            }
            if !pad_on_paste_side(pad.side, false, top) {
                continue;
            }
            let shrink = match pad.solder_paste {
                SolderPasteConfig::Auto => {
                    let ratio = rules.solderpaste_clearance_ratio;
                    let min_s = rules.solderpaste_clearance_min;
                    let max_s = rules.solderpaste_clearance_max;
                    let computed = pad.size_width.min(pad.size_height) * ratio;
                    computed.max(min_s).min(max_s)
                }
                SolderPasteConfig::Manual(v) => v,
                SolderPasteConfig::Off => continue,
            };
            let w = (pad.size_width - 2.0 * shrink).max(0.01);
            let h = (pad.size_height - 2.0 * shrink).max(0.01);
            let ap = match pad.shape {
                PadShape::Round => cache.circle(&mut writer, w),
                _ => cache.rectangle(&mut writer, w, h),
            };
            flashes.push((ap, pad.position.x, pad.position.y));
        }
    }

    // No vias on paste layer — ever.

    writer.set_polarity_dark();
    for (ap, x, y) in &flashes {
        writer.select_aperture(*ap);
        writer.flash(*x, *y);
    }

    writer.finish();
    Ok(writer.to_string())
}

fn pad_on_paste_side(pad_side: PadSide, flipped: bool, top: bool) -> bool {
    let side = effective_pad_side(pad_side, flipped);
    if top {
        matches!(side, PadSide::Top)
    } else {
        matches!(side, PadSide::Bottom)
    }
}

fn paste_shrink_auto(fp_pad: &FootprintPad, rules: &DesignRules) -> f64 {
    let ratio = rules.solderpaste_clearance_ratio;
    let min_s = rules.solderpaste_clearance_min;
    let max_s = rules.solderpaste_clearance_max;
    let pad_min = fp_pad.width.min(fp_pad.height);
    let computed = pad_min * ratio;
    computed.max(min_s).min(max_s)
}

// ═══════════════════════════════════════════════════════════════════════════
// Silkscreen layer export
// ═══════════════════════════════════════════════════════════════════════════

/// Export a silkscreen (legend) layer as a Gerber RS-274X string.
///
/// Renders footprint outlines and board-level polygons on the legend layer.
pub fn export_silkscreen_layer(
    board: &Board,
    _circuit: &Circuit,
    library: &dyn BoardLibrary,
    top: bool,
) -> Result<String> {
    let file_function = if top { "Legend,Top" } else { "Legend,Bot" };
    let mut writer = GerberWriter::new_x2(file_function, "Positive");
    let mut cache = ApertureCache::new();

    let target_layer = if top {
        Layer::TopLegend
    } else {
        Layer::BottomLegend
    };

    let side_name = if top { "Top" } else { "Bottom" };
    writer.comment(&format!("Silkscreen {}", side_name));
    writer.set_polarity_dark();

    // Footprint polygons on legend layers
    for dev in &board.devices {
        let Some(lib_dev) = library.get_device(&dev.lib_device) else {
            continue;
        };
        let Some(pkg) = library.get_package(&lib_dev.package) else {
            continue;
        };
        let Some(footprint) = pkg.footprints.iter().find(|f| f.uuid == dev.lib_footprint) else {
            continue;
        };
        for poly in &footprint.polygons {
            // Account for device flip when mapping layers.
            let poly_layer = if dev.flip {
                match poly.layer {
                    Layer::TopLegend => Layer::BottomLegend,
                    Layer::BottomLegend => Layer::TopLegend,
                    other => other,
                }
            } else {
                poly.layer
            };
            if poly_layer != target_layer {
                continue;
            }
            if poly.vertices.len() < 2 {
                continue;
            }
            let line_width = if poly.width > 0.0 { poly.width } else { 0.15 };
            let ap = cache.circle(&mut writer, line_width);
            writer.select_aperture(ap);

            let first = transform_point(
                poly.vertices[0].position.x,
                poly.vertices[0].position.y,
                dev,
            );
            writer.move_to(first.0, first.1);
            for v in &poly.vertices[1..] {
                let (x, y) = transform_point(v.position.x, v.position.y, dev);
                writer.line_to(x, y);
            }
            // Close polygon
            if poly.vertices.len() > 2 {
                writer.line_to(first.0, first.1);
            }
        }
    }

    // Board-level polygons on legend layers
    for poly in &board.polygons {
        if poly.layer != target_layer {
            continue;
        }
        if poly.vertices.len() < 2 {
            continue;
        }
        let line_width = if poly.width > 0.0 { poly.width } else { 0.15 };
        let ap = cache.circle(&mut writer, line_width);
        writer.select_aperture(ap);

        writer.move_to(poly.vertices[0].position.x, poly.vertices[0].position.y);
        for v in &poly.vertices[1..] {
            writer.line_to(v.position.x, v.position.y);
        }
        if poly.vertices.len() > 2 {
            writer.line_to(poly.vertices[0].position.x, poly.vertices[0].position.y);
        }
    }

    writer.finish();
    Ok(writer.to_string())
}

// ═══════════════════════════════════════════════════════════════════════════
// Board outline export
// ═══════════════════════════════════════════════════════════════════════════

/// Export the board outline as a Gerber RS-274X string.
///
/// The outline is drawn from the first [`BoardPolygon`] on the
/// [`Layer::BoardOutlines`] layer.
pub fn export_board_outline(board: &Board) -> Result<String> {
    let outline = board
        .polygons
        .iter()
        .find(|p| p.layer == Layer::BoardOutlines)
        .ok_or(GerberError::NoBoardOutline)?;

    if outline.vertices.is_empty() {
        return Err(GerberError::NoBoardOutline);
    }

    let mut writer = GerberWriter::new_x2("Profile,NP", "Positive");
    writer.comment("Board Outline");

    // Use a thin line for the outline routing path.
    let ap = writer.add_aperture(Aperture::Circle { diameter: 0.05 });
    writer.set_polarity_dark();
    writer.select_aperture(ap);

    let first = &outline.vertices[0];
    writer.move_to(first.position.x, first.position.y);
    for v in &outline.vertices[1..] {
        writer.line_to(v.position.x, v.position.y);
    }
    // Close the outline path
    writer.line_to(first.position.x, first.position.y);

    writer.finish();
    Ok(writer.to_string())
}

// ═══════════════════════════════════════════════════════════════════════════
// Export all layers
// ═══════════════════════════════════════════════════════════════════════════

/// Summary of files written by [`export_all`].
#[derive(Debug)]
pub struct ExportSummary {
    pub files: Vec<ExportedFile>,
}

/// A single exported Gerber file.
#[derive(Debug)]
pub struct ExportedFile {
    pub path: PathBuf,
    pub layer_name: String,
}

/// Helper to write a single Gerber file and record it in the summary.
fn write_gerber_file(
    files: &mut Vec<ExportedFile>,
    output_dir: &Path,
    board_name: &str,
    suffix: &str,
    layer_name: &str,
    content: &str,
) -> Result<()> {
    let filename = format!("{}{}", board_name, suffix);
    let path = output_dir.join(filename);
    std::fs::write(&path, content)?;
    files.push(ExportedFile {
        path,
        layer_name: layer_name.to_string(),
    });
    Ok(())
}

/// Export all fabrication layers for a board to the given output directory.
///
/// Writes Gerber files for:
/// - Board outline
/// - Top and bottom copper
/// - Inner copper layers (if any)
/// - Top and bottom soldermask
/// - Top and bottom silkscreen
///
/// File names are formed as `{board.name}{suffix}` using the suffixes
/// from [`FabricationOutputSettings`].
pub fn export_all(
    board: &Board,
    circuit: &Circuit,
    library: &dyn BoardLibrary,
    output_dir: &Path,
) -> Result<ExportSummary> {
    std::fs::create_dir_all(output_dir)?;

    let settings = &board.fabrication_output_settings;
    let name = &board.name;
    let mut files = Vec::new();

    // Board outline
    let content = export_board_outline(board)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.outlines_suffix,
        "Board Outlines",
        &content,
    )?;

    // Top copper
    let content = export_copper_layer(board, circuit, library, Layer::TopCopper)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.copper_top_suffix,
        "Top Copper",
        &content,
    )?;

    // Bottom copper
    let content = export_copper_layer(board, circuit, library, Layer::BottomCopper)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.copper_bot_suffix,
        "Bottom Copper",
        &content,
    )?;

    // Inner copper layers
    for i in 1..=board.inner_layers {
        let layer = Layer::InnerCopper(i);
        let content = export_copper_layer(board, circuit, library, layer)?;
        let suffix = settings
            .copper_inner_suffix
            .replace("{{CU_LAYER}}", &i.to_string());
        let layer_name = format!("Inner Copper {}", i);
        write_gerber_file(&mut files, output_dir, name, &suffix, &layer_name, &content)?;
    }

    // Soldermask
    let content = export_soldermask_layer(board, circuit, library, true)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.soldermask_top_suffix,
        "Top Soldermask",
        &content,
    )?;

    let content = export_soldermask_layer(board, circuit, library, false)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.soldermask_bot_suffix,
        "Bottom Soldermask",
        &content,
    )?;

    // Silkscreen
    let content = export_silkscreen_layer(board, circuit, library, true)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.silkscreen_top_suffix,
        "Top Silkscreen",
        &content,
    )?;

    let content = export_silkscreen_layer(board, circuit, library, false)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.silkscreen_bot_suffix,
        "Bottom Silkscreen",
        &content,
    )?;

    // Solder paste / stencil
    let content = export_paste_layer(board, circuit, library, true)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.paste_top_suffix,
        "Top Paste",
        &content,
    )?;

    let content = export_paste_layer(board, circuit, library, false)?;
    write_gerber_file(
        &mut files,
        output_dir,
        name,
        &settings.paste_bot_suffix,
        "Bottom Paste",
        &content,
    )?;

    Ok(ExportSummary { files })
}

// ═══════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helper: default design rules via serde ───────────────────────────

    fn default_design_rules() -> DesignRules {
        serde_json::from_str("{}").unwrap()
    }

    fn default_drc_settings() -> DrcSettings {
        serde_json::from_str("{}").unwrap()
    }

    fn default_grid() -> Grid {
        Grid {
            interval: 2.54,
            unit: GridUnit::Millimeters,
        }
    }

    /// Build a minimal board with a single trace (junction → junction) on
    /// TopCopper.
    fn make_board_with_trace() -> Board {
        let j1 = Uuid::new_v4();
        let j2 = Uuid::new_v4();

        Board {
            uuid: Uuid::new_v4(),
            name: "test_board".to_string(),
            grid: default_grid(),
            inner_layers: 0,
            thickness: 1.6,
            solder_resist: SolderResistColor::Green,
            silkscreen: SilkscreenColor::White,
            default_font: "newstroke.bene".to_string(),
            design_rules: default_design_rules(),
            drc_settings: default_drc_settings(),
            fabrication_output_settings: FabricationOutputSettings::default(),
            devices: vec![],
            net_segments: vec![BoardNetSegment {
                uuid: Uuid::new_v4(),
                net: Some(Uuid::new_v4()),
                traces: vec![Trace {
                    uuid: Uuid::new_v4(),
                    layer: Layer::TopCopper,
                    width: 0.25,
                    from: TraceEndpoint::Junction { junction: j1 },
                    to: TraceEndpoint::Junction { junction: j2 },
                }],
                vias: vec![],
                junctions: vec![
                    Junction {
                        uuid: j1,
                        position: Position::new(0.0, 0.0),
                    },
                    Junction {
                        uuid: j2,
                        position: Position::new(10.0, 5.0),
                    },
                ],
                pads: vec![],
            }],
            planes: vec![],
            polygons: vec![],
            holes: vec![],
        }
    }

    /// Build a minimal board with a BoardOutlines polygon (a rectangle).
    fn make_board_with_outline() -> Board {
        Board {
            uuid: Uuid::new_v4(),
            name: "outline_test".to_string(),
            grid: default_grid(),
            inner_layers: 0,
            thickness: 1.6,
            solder_resist: SolderResistColor::Green,
            silkscreen: SilkscreenColor::White,
            default_font: "newstroke.bene".to_string(),
            design_rules: default_design_rules(),
            drc_settings: default_drc_settings(),
            fabrication_output_settings: FabricationOutputSettings::default(),
            devices: vec![],
            net_segments: vec![],
            planes: vec![],
            polygons: vec![BoardPolygon {
                uuid: Uuid::new_v4(),
                layer: Layer::BoardOutlines,
                width: 0.0,
                fill: false,
                grab_area: false,
                lock: false,
                vertices: vec![
                    Vertex {
                        position: Position::new(0.0, 0.0),
                        angle: Angle(0.0),
                    },
                    Vertex {
                        position: Position::new(100.0, 0.0),
                        angle: Angle(0.0),
                    },
                    Vertex {
                        position: Position::new(100.0, 80.0),
                        angle: Angle(0.0),
                    },
                    Vertex {
                        position: Position::new(0.0, 80.0),
                        angle: Angle(0.0),
                    },
                ],
            }],
            holes: vec![],
        }
    }

    // ── GerberWriter unit tests ──────────────────────────────────────────

    #[test]
    fn coordinate_formatting() {
        let writer = GerberWriter::new();
        assert_eq!(writer.format_coord(0.0), "0");
        assert_eq!(writer.format_coord(1.0), "1000000");
        assert_eq!(writer.format_coord(10.5), "10500000");
        assert_eq!(writer.format_coord(-5.25), "-5250000");
        assert_eq!(writer.format_coord(0.001), "1000");
    }

    #[test]
    fn coordinate_formatting_rounding() {
        let writer = GerberWriter::new();
        // 0.0000005 → rounds to 1 (at the nanometre level)
        assert_eq!(writer.format_coord(0.0000005), "1");
        // Large value
        assert_eq!(writer.format_coord(999.999999), "999999999");
    }

    #[test]
    fn writer_header_structure() {
        let writer = GerberWriter::new();
        let output = writer.to_string();
        assert!(output.contains("%FSLAX46Y46*%"));
        assert!(output.contains("%MOMM*%"));
        assert!(output.contains("%IPPOS*%"));
        assert!(output.contains("G04 Generated by Volt EDA"));
    }

    #[test]
    fn writer_aperture_definitions() {
        let mut writer = GerberWriter::new();
        let i0 = writer.add_aperture(Aperture::Circle { diameter: 0.25 });
        let i1 = writer.add_aperture(Aperture::Rectangle {
            width: 1.5,
            height: 0.6,
        });
        assert_eq!(i0, 0);
        assert_eq!(i1, 1);

        let output = writer.to_string();
        assert!(output.contains("%ADD10C,0.250000*%"));
        assert!(output.contains("%ADD11R,1.500000X0.600000*%"));
    }

    #[test]
    fn writer_draw_commands() {
        let mut writer = GerberWriter::new();
        writer.add_aperture(Aperture::Circle { diameter: 0.2 });
        writer.select_aperture(0);
        writer.move_to(5.0, 10.0);
        writer.line_to(15.0, 20.0);
        writer.flash(25.0, 30.0);
        writer.finish();

        let output = writer.to_string();
        assert!(output.contains("D10*"));
        assert!(output.contains("X5000000Y10000000D02*"));
        assert!(output.contains("X15000000Y20000000D01*"));
        assert!(output.contains("X25000000Y30000000D03*"));
        assert!(output.contains("M02*"));
    }

    #[test]
    fn writer_polarity_and_regions() {
        let mut writer = GerberWriter::new();
        writer.set_polarity_dark();
        writer.set_polarity_clear();
        writer.region_start();
        writer.region_end();

        let output = writer.to_string();
        assert!(output.contains("%LPD*%"));
        assert!(output.contains("%LPC*%"));
        assert!(output.contains("G36*"));
        assert!(output.contains("G37*"));
    }

    #[test]
    fn aperture_deduplication() {
        let mut writer = GerberWriter::new();
        let mut cache = ApertureCache::new();

        let a = cache.circle(&mut writer, 0.25);
        let b = cache.circle(&mut writer, 0.25);
        let c = cache.circle(&mut writer, 0.5);
        assert_eq!(a, b); // same aperture reused
        assert_ne!(a, c); // different diameter → different aperture
    }

    // ── Copper layer export ──────────────────────────────────────────────

    #[test]
    fn copper_layer_simple_trace() {
        let board = make_board_with_trace();
        let circuit = Circuit::default();
        let library = MapBoardLibrary::new();

        let result = export_copper_layer(&board, &circuit, &library, Layer::TopCopper).unwrap();

        // Header
        assert!(result.contains("%FSLAX46Y46*%"));
        assert!(result.contains("%MOMM*%"));

        // Aperture for 0.25mm trace
        assert!(result.contains("%ADD10C,0.250000*%"));

        // Draw commands: move to (0,0) then draw to (10, 5)
        assert!(result.contains("X0Y0D02*"));
        assert!(result.contains("X10000000Y5000000D01*"));

        // End of file
        assert!(result.contains("M02*"));
    }

    #[test]
    fn copper_layer_wrong_layer_produces_no_draws() {
        let board = make_board_with_trace();
        let circuit = Circuit::default();
        let library = MapBoardLibrary::new();

        let result = export_copper_layer(&board, &circuit, &library, Layer::BottomCopper).unwrap();

        // No trace aperture should appear (the trace is on TopCopper only)
        assert!(!result.contains("D01*"), "no draw commands expected");
        // But the file is still valid Gerber
        assert!(result.contains("M02*"));
    }

    // ── Board outline export ─────────────────────────────────────────────

    #[test]
    fn board_outline_valid_gerber() {
        let board = make_board_with_outline();
        let result = export_board_outline(&board).unwrap();

        assert!(result.contains("%FSLAX46Y46*%"));
        assert!(result.contains("M02*"));
        // Should have move + 4 line draws (3 edges + close)
        assert!(result.contains("D02*")); // move to first vertex
        let d01_count = result.matches("D01*").count();
        assert_eq!(d01_count, 4, "expected 4 line segments for a rectangle");
    }

    #[test]
    fn board_outline_contains_expected_coordinates() {
        let board = make_board_with_outline();
        let result = export_board_outline(&board).unwrap();

        // Vertices: (0,0), (100,0), (100,80), (0,80)
        assert!(result.contains("X0Y0D02*")); // move to start
        assert!(result.contains("X100000000Y0D01*")); // draw to (100,0)
        assert!(result.contains("X100000000Y80000000D01*")); // draw to (100,80)
        assert!(result.contains("X0Y80000000D01*")); // draw to (0,80)
        assert!(result.contains("X0Y0D01*")); // close back to (0,0)
    }

    #[test]
    fn board_outline_missing_returns_error() {
        let mut board = make_board_with_outline();
        board.polygons.clear();

        let result = export_board_outline(&board);
        assert!(result.is_err());
    }

    // ── Transform helper ─────────────────────────────────────────────────

    #[test]
    fn transform_point_no_rotation_no_flip() {
        let dev = BoardDevice {
            component: Uuid::new_v4(),
            lib_device: Uuid::new_v4(),
            lib_footprint: Uuid::new_v4(),
            position: Position::new(10.0, 20.0),
            rotation: Angle(0.0),
            flip: false,
            lock: false,
            texts: vec![],
        };
        let (x, y) = transform_point(1.0, 2.0, &dev);
        assert!((x - 11.0).abs() < 1e-9);
        assert!((y - 22.0).abs() < 1e-9);
    }

    #[test]
    fn transform_point_90_deg_rotation() {
        let dev = BoardDevice {
            component: Uuid::new_v4(),
            lib_device: Uuid::new_v4(),
            lib_footprint: Uuid::new_v4(),
            position: Position::new(0.0, 0.0),
            rotation: Angle(90.0),
            flip: false,
            lock: false,
            texts: vec![],
        };
        // Rotating (1, 0) by 90° → (0, 1)
        let (x, y) = transform_point(1.0, 0.0, &dev);
        assert!((x - 0.0).abs() < 1e-9, "x = {}", x);
        assert!((y - 1.0).abs() < 1e-9, "y = {}", y);
    }

    #[test]
    fn transform_point_flip() {
        let dev = BoardDevice {
            component: Uuid::new_v4(),
            lib_device: Uuid::new_v4(),
            lib_footprint: Uuid::new_v4(),
            position: Position::new(0.0, 0.0),
            rotation: Angle(0.0),
            flip: true,
            lock: false,
            texts: vec![],
        };
        // Flip mirrors X
        let (x, y) = transform_point(3.0, 4.0, &dev);
        assert!((x - (-3.0)).abs() < 1e-9);
        assert!((y - 4.0).abs() < 1e-9);
    }

    // ── Via helpers ──────────────────────────────────────────────────────

    #[test]
    fn via_on_layer_through_hole() {
        let via = Via {
            uuid: Uuid::new_v4(),
            from_layer: Layer::TopCopper,
            to_layer: Layer::BottomCopper,
            position: Position::new(0.0, 0.0),
            drill: 0.3,
            size: ViaSize::Auto,
            exposure: ViaExposure::Auto,
        };
        assert!(via_on_layer(&via, Layer::TopCopper));
        assert!(via_on_layer(&via, Layer::BottomCopper));
        assert!(via_on_layer(&via, Layer::InnerCopper(1)));
        assert!(!via_on_layer(&via, Layer::TopLegend));
    }

    #[test]
    fn via_diameter_auto() {
        let rules = default_design_rules();
        let via = Via {
            uuid: Uuid::new_v4(),
            from_layer: Layer::TopCopper,
            to_layer: Layer::BottomCopper,
            position: Position::new(0.0, 0.0),
            drill: 0.3,
            size: ViaSize::Auto,
            exposure: ViaExposure::Auto,
        };
        let d = compute_via_diameter(&via, &rules);
        // With default rules: ring = clamp(0.25 * 0.3, 0.2, 2.0) = 0.2
        // diameter = 0.3 + 2 * 0.2 = 0.7
        assert!((d - 0.7).abs() < 1e-9, "diameter = {}", d);
    }

    #[test]
    fn via_diameter_manual() {
        let rules = default_design_rules();
        let via = Via {
            uuid: Uuid::new_v4(),
            from_layer: Layer::TopCopper,
            to_layer: Layer::BottomCopper,
            position: Position::new(0.0, 0.0),
            drill: 0.3,
            size: ViaSize::Manual(1.0),
            exposure: ViaExposure::Auto,
        };
        let d = compute_via_diameter(&via, &rules);
        assert!((d - 1.0).abs() < 1e-9);
    }
}
