//! IPC-D-356 bare-board test netlist export.
//!
//! Generates an IPC-D-356 netlist file for electrical test fixtures.
//! Uses 317 records for through-hole test points and 327 records for SMD.

use std::collections::HashMap;
use std::fmt::Write;
use std::path::Path;

use uuid::Uuid;

use volt_core::common::*;
use volt_core::library::{Device, FootprintPad, Package, PackagePad};
use volt_core::project::*;

use crate::gerber::{BoardLibrary, transform_point};

/// Generate an IPC-D-356 netlist string.
pub fn export_ipc_d356(
    board: &Board,
    circuit: &Circuit,
    library: &dyn BoardLibrary,
) -> String {
    let mut out = String::with_capacity(4096);

    // Header
    writeln!(out, "C  IPC-D-356 Netlist").unwrap();
    writeln!(out, "C  Generated by Volt EDA").unwrap();
    writeln!(out, "C  Board: {}", board.name).unwrap();
    writeln!(out, "P  JOB   {}", board.name).unwrap();
    writeln!(out, "P  UNITS CUST 1").unwrap(); // units: mils (thousandths of inch)
    writeln!(out, "C").unwrap();

    // Build net name lookup
    let net_names: HashMap<Uuid, String> = circuit
        .nets
        .iter()
        .map(|n| (n.uuid, n.name.clone()))
        .collect();

    // Build component designator lookup
    let comp_names: HashMap<Uuid, String> = circuit
        .components
        .iter()
        .map(|c| (c.uuid, c.name.clone()))
        .collect();

    // Build pad→net map
    let pad_net_map = build_pad_net_map(board, circuit, library);

    // Iterate devices and their pads
    for dev in &board.devices {
        let Some(lib_dev) = library.get_device(&dev.lib_device) else { continue };
        let Some(pkg) = library.get_package(&lib_dev.package) else { continue };
        let Some(fp) = pkg.footprints.iter().find(|f| f.uuid == dev.lib_footprint)
            .or_else(|| pkg.footprints.first()) else { continue };

        let designator = comp_names.get(&dev.component).map(|s| s.as_str()).unwrap_or("?");

        for fp_pad in &fp.pads {
            let pad_name = pkg.pads.iter()
                .find(|p| p.uuid == fp_pad.package_pad)
                .map(|p| p.name.as_str())
                .unwrap_or("?");

            let net_uuid = pad_net_map.get(&(dev.component, fp_pad.uuid));
            let net_name = net_uuid
                .and_then(|n| net_names.get(n))
                .map(|s| s.as_str())
                .unwrap_or("N/C");

            let (wx, wy) = transform_point(fp_pad.position.x, fp_pad.position.y, dev);
            // Convert mm to mils (thousandths of inch)
            let x_mil = (wx * 1000.0 / 25.4) as i32;
            let y_mil = (wy * 1000.0 / 25.4) as i32;

            let is_tht = fp_pad.side == PadSide::ThroughHole || !fp_pad.holes.is_empty();
            let hole_dia_mil = fp_pad.holes.first()
                .map(|h| (h.diameter * 1000.0 / 25.4) as i32)
                .unwrap_or(0);

            let record_type = if is_tht { "317" } else { "327" };
            let access = if is_tht {
                "A00" // accessible from both sides
            } else {
                match effective_pad_side_d356(fp_pad.side, dev.flip) {
                    PadSide::Top => "A01",
                    PadSide::Bottom => "A02",
                    _ => "A00",
                }
            };

            // Pad size in mils
            let pad_w_mil = (fp_pad.width * 1000.0 / 25.4) as i32;
            let pad_h_mil = (fp_pad.height * 1000.0 / 25.4) as i32;

            // Format: 317 NET COMP-PAD  ACCESS X Y SIZE HOLE
            writeln!(
                out,
                "{}  {:<14}{:<6}-{:<4}   {}X{:+07}Y{:+07}X{:04}Y{:04}X{:04}   ",
                record_type,
                &net_name[..net_name.len().min(14)],
                &designator[..designator.len().min(6)],
                &pad_name[..pad_name.len().min(4)],
                access,
                x_mil, y_mil,
                pad_w_mil, pad_h_mil,
                hole_dia_mil,
            ).unwrap();
        }
    }

    // End record
    writeln!(out, "999").unwrap();
    out
}

fn effective_pad_side_d356(pad_side: PadSide, flipped: bool) -> PadSide {
    if !flipped { return pad_side; }
    match pad_side {
        PadSide::Top => PadSide::Bottom,
        PadSide::Bottom => PadSide::Top,
        PadSide::ThroughHole => PadSide::ThroughHole,
    }
}

fn build_pad_net_map(
    board: &Board,
    circuit: &Circuit,
    library: &dyn BoardLibrary,
) -> HashMap<(Uuid, Uuid), Uuid> {
    let mut map = HashMap::new();
    for dev in &board.devices {
        let Some(device_lib) = library.get_device(&dev.lib_device) else { continue };
        let Some(package) = library.get_package(&device_lib.package) else { continue };
        let comp = circuit.components.iter().find(|c| c.uuid == dev.component);
        let Some(comp) = comp else { continue };
        let footprint = package.footprints.iter()
            .find(|f| f.uuid == dev.lib_footprint)
            .or_else(|| package.footprints.first());
        let Some(footprint) = footprint else { continue };

        for fp_pad in &footprint.pads {
            let signal = device_lib.pad_mappings.iter()
                .find(|pm| pm.pad == fp_pad.package_pad)
                .map(|pm| pm.signal);
            if let Some(sig) = signal {
                let net = comp.signal_connections.iter()
                    .find(|sc| sc.signal == sig)
                    .and_then(|sc| sc.net);
                if let Some(net_uuid) = net {
                    map.insert((dev.component, fp_pad.uuid), net_uuid);
                }
            }
        }
    }
    map
}
