#pragma once

#include <volt/authoring/component_library.hpp>
#include <volt/authoring/connection_helpers.hpp>
#include <volt/authoring/reference_designators.hpp>
#include <volt/circuit/bom/bom.hpp>
#include <volt/circuit/circuit.hpp>
#include <volt/circuit/connectivity/definitions.hpp>
#include <volt/circuit/connectivity/instances.hpp>
#include <volt/circuit/connectivity/nets.hpp>
#include <volt/circuit/connectivity/queries.hpp>
#include <volt/circuit/constraints/net_classes.hpp>
#include <volt/circuit/electrical/queries.hpp>
#include <volt/circuit/electrical/records.hpp>
#include <volt/circuit/hierarchy/hierarchy.hpp>
#include <volt/circuit/intent/design_intent.hpp>
#include <volt/circuit/parts/part_definition.hpp>
#include <volt/circuit/parts/parts.hpp>
#include <volt/circuit/validation/validation.hpp>
#include <volt/core/content_hash.hpp>
#include <volt/core/diagnostics.hpp>
#include <volt/core/electrical_attributes.hpp>
#include <volt/core/entity_ref.hpp>
#include <volt/core/entity_table.hpp>
#include <volt/core/errors.hpp>
#include <volt/core/ids.hpp>
#include <volt/core/properties.hpp>
#include <volt/core/quantities.hpp>
#include <volt/core/rule_set.hpp>
#include <volt/core/version.hpp>
#include <volt/io/assembly/cpl_writer.hpp>
#include <volt/io/bom/bom_writer.hpp>
#include <volt/io/capabilities/board_capability_profile.hpp>
#include <volt/io/logical/logical_circuit_reader.hpp>
#include <volt/io/logical/logical_circuit_writer.hpp>
#include <volt/io/parts/electrical_records_io.hpp>
#include <volt/io/parts/part_definition_reader.hpp>
#include <volt/io/parts/part_definition_writer.hpp>
#include <volt/io/pcb/pcb_fabrication_writer.hpp>
#include <volt/io/pcb/pcb_reader.hpp>
#include <volt/io/pcb/pcb_schema.hpp>
#include <volt/io/pcb/pcb_svg_writer.hpp>
#include <volt/io/pcb/pcb_writer.hpp>
#include <volt/io/schematic/schematic_reader.hpp>
#include <volt/io/schematic/schematic_schema.hpp>
#include <volt/io/schematic/schematic_svg_writer.hpp>
#include <volt/io/schematic/schematic_writer.hpp>
#include <volt/pcb/assembly/cpl.hpp>
#include <volt/pcb/board.hpp>
#include <volt/pcb/copper/board_copper_model.hpp>
#include <volt/pcb/footprints/board_footprint_model.hpp>
#include <volt/pcb/footprints/footprints.hpp>
#include <volt/pcb/placement/board_placement_model.hpp>
#include <volt/pcb/projection/board_geometry_projection.hpp>
#include <volt/pcb/queries/board_queries.hpp>
#include <volt/pcb/routing/board_router.hpp>
#include <volt/pcb/routing/board_spatial_index.hpp>
#include <volt/pcb/structure/board_structure_model.hpp>
#include <volt/schematic/default_symbols.hpp>
#include <volt/schematic/geometry.hpp>
#include <volt/schematic/layout.hpp>
#include <volt/schematic/schematic.hpp>
#include <volt/schematic/schematic_document.hpp>
#include <volt/schematic/symbols.hpp>
#include <volt/schematic/validation.hpp>
