"""Types for native linear AC requests. Common references use the exact DC input."""
from typing import Iterable
from .dc import (DcInput as AcInput, DcInputIdentity as AcInputIdentity,
                 DcNetRef as AcNetRef, DcOccurrenceRef as AcOccurrenceRef,
                 DcRequestKey as AcRequestKey, DcSourceKey as AcSourceKey,
                 DcProbeKey as AcProbeKey, DcNetPair as AcNetPair,
                 DcVoltageProbe as AcVoltageProbe,
                 DcSourceCurrentProbe as AcSourceCurrentProbe,
                 DcModelElementCurrentProbe as AcModelElementCurrentProbe,
                 DcOccurrenceExclusion as AcOccurrenceExclusion,
                 DcNonElectricalExclusion as AcNonElectricalExclusion,
                 DcOutsideAnalysisExclusion as AcOutsideAnalysisExclusion,
                 DcReplacedByStimulusExclusion as AcReplacedByStimulusExclusion,
                 DcProbe, DcOccurrenceCoverage, prepare_dc_input as prepare_ac_input)
from .electrical import Quantity

class AcFrequencySweep:
    def __init__(self, frequencies: Iterable[Quantity]) -> None: ...
    @staticmethod
    def linear(start: Quantity, stop: Quantity, count: int) -> AcFrequencySweep: ...
    @staticmethod
    def logarithmic(start: Quantity, stop: Quantity, count: int) -> AcFrequencySweep: ...
    @property
    def frequencies(self) -> tuple[Quantity, ...]: ...

class _AcVoltageSource:
    @property
    def key(self) -> AcSourceKey: ...
    @property
    def nets(self) -> AcNetPair: ...
    @property
    def amplitude(self) -> Quantity: ...
    @property
    def phase(self) -> float: ...
    @property
    def phasor(self) -> complex: ...

class _AcCurrentSource:
    @property
    def key(self) -> AcSourceKey: ...
    @property
    def nets(self) -> AcNetPair: ...
    @property
    def amplitude(self) -> Quantity: ...
    @property
    def phase(self) -> float: ...
    @property
    def phasor(self) -> complex: ...

def AcVoltageSource(key: AcSourceKey | str, from_: AcNetRef, to: AcNetRef,
                    amplitude: Quantity, phase: float = 0.0) -> _AcVoltageSource: ...
def AcCurrentSource(key: AcSourceKey | str, from_: AcNetRef, to: AcNetRef,
                    amplitude: Quantity, phase: float = 0.0) -> _AcCurrentSource: ...

class AcRequestAssessment:
    @property
    def complete(self) -> bool: ...
    @property
    def input(self) -> AcInputIdentity: ...
    @property
    def coverage(self) -> tuple[DcOccurrenceCoverage, ...]: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...

class AcRequest:
    def __init__(self, key: AcRequestKey | str, input: AcInput, sweep: AcFrequencySweep,
                 reference: AcNetRef | None = None,
                 sources: Iterable[_AcVoltageSource | _AcCurrentSource] = (),
                 probes: Iterable[DcProbe] = (),
                 exclusions: Iterable[AcOccurrenceExclusion] = (),
                 gains: Iterable[AcGainProbe] = (), impedances: Iterable[_AcImpedanceProbe] = ()) -> None: ...
    @property
    def key(self) -> AcRequestKey: ...
    @property
    def input(self) -> AcInput: ...
    @property
    def reference(self) -> AcNetRef | None: ...
    @property
    def sweep(self) -> AcFrequencySweep: ...
    @property
    def frequencies(self) -> tuple[Quantity, ...]: ...
    @property
    def sources(self) -> tuple[_AcVoltageSource | _AcCurrentSource, ...]: ...
    @property
    def probes(self) -> tuple[DcProbe, ...]: ...
    @property
    def exclusions(self) -> tuple[AcOccurrenceExclusion, ...]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(input: AcInput, data: bytes | str) -> AcRequest: ...
    @property
    def gains(self) -> tuple[AcGainProbe, ...]: ...
    @property
    def impedances(self) -> tuple[_AcImpedanceProbe, ...]: ...
    def assess(self) -> AcRequestAssessment: ...
def assess_ac_request(request: AcRequest) -> AcRequestAssessment: ...

class AcGainProbe:
    def __init__(self, key: AcProbeKey | str, numerator: AcProbeKey | str, denominator: AcProbeKey | str) -> None: ...
    @property
    def key(self) -> AcProbeKey: ...
    @property
    def numerator(self) -> AcProbeKey: ...
    @property
    def denominator(self) -> AcProbeKey: ...
class _AcImpedanceProbe:
    @property
    def key(self) -> AcProbeKey: ...
    @property
    def nets(self) -> AcNetPair: ...
    @property
    def source(self) -> AcSourceKey: ...
def AcImpedanceProbe(key: AcProbeKey | str, from_: AcNetRef, to: AcNetRef, source: AcSourceKey | str) -> _AcImpedanceProbe: ...
