from .dc_solve import DcSolveOptions, DcSolveProvenance as AcSolveProvenance
from .electrical import Quantity, UnitDimension, ContentHash
from .compilation import CompiledElectricalModel
from .dc import ElectricalProbeKey
from enum import Enum

class AcComplexQuantity:
    def __init__(self, dimension: UnitDimension, real: float, imaginary: float) -> None: ...
    @property
    def dimension(self) -> UnitDimension: ...
    @property
    def real(self) -> float: ...
    @property
    def imaginary(self) -> float: ...
    @property
    def value(self) -> complex: ...
    @property
    def magnitude(self) -> float: ...
    @property
    def phase(self) -> float | None: ...
class AcSolveOptions(DcSolveOptions): ...
class AcSolveMetrics:
    @property
    def coordinate_count(self) -> int: ...
    @property
    def rank(self) -> int | None: ...
    @property
    def augmented_rank(self) -> int | None: ...
    @property
    def reciprocal_condition(self) -> float | None: ...
    @property
    def scaled_residual(self) -> float | None: ...
    @property
    def voltage_residual(self) -> Quantity | None: ...
    @property
    def current_residual(self) -> Quantity | None: ...
    @property
    def voltage_error_ratio(self) -> float | None: ...
    @property
    def current_error_ratio(self) -> float | None: ...


class AcSolveOutcome(Enum):
    SUCCESS = ...
    RANK_DEFICIENT = ...
    INCONSISTENT = ...
    ILL_CONDITIONED = ...
    NUMERICAL_FAILURE = ...
    RESIDUAL_FAILURE = ...
    UNDEFINED_MEASUREMENT = ...
class AcNodeResult:
    @property
    def node(self) -> int: ...
    @property
    def potential(self) -> AcComplexQuantity: ...
class AcBranchResult:
    @property
    def branch(self) -> int: ...
    @property
    def voltage(self) -> AcComplexQuantity: ...
    @property
    def current(self) -> AcComplexQuantity: ...
class AcProbeResult:
    @property
    def key(self) -> ElectricalProbeKey: ...
    @property
    def value(self) -> AcComplexQuantity: ...
class AcFrequencyResult:
    @property
    def frequency(self) -> Quantity: ...
    @property
    def nodes(self) -> tuple[AcNodeResult, ...]: ...
    @property
    def branches(self) -> tuple[AcBranchResult, ...]: ...
    @property
    def probes(self) -> tuple[AcProbeResult, ...]: ...
class AcPointReport:
    @property
    def frequency(self) -> Quantity: ...
    @property
    def outcome(self) -> AcSolveOutcome: ...
    @property
    def metrics(self) -> AcSolveMetrics: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
class AcSolution:
    @property
    def analysis_identity(self) -> ContentHash: ...
    @property
    def model(self) -> CompiledElectricalModel: ...
    @property
    def options(self) -> AcSolveOptions: ...
    @property
    def provenance(self) -> AcSolveProvenance: ...
    @property
    def points(self) -> tuple[AcFrequencyResult, ...]: ...
    def to_json(self) -> str: ...
class AcSolveReport:
    @property
    def contract_version(self) -> int: ...
    @property
    def backend(self) -> str: ...
    @property
    def analysis_identity(self) -> ContentHash: ...
    @property
    def model(self) -> CompiledElectricalModel: ...
    @property
    def options(self) -> AcSolveOptions: ...
    @property
    def provenance(self) -> AcSolveProvenance: ...
    @property
    def outcome(self) -> AcSolveOutcome: ...
    @property
    def success(self) -> bool: ...
    @property
    def points(self) -> tuple[AcPointReport, ...]: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
    @property
    def solution(self) -> AcSolution | None: ...
    def to_json(self) -> str: ...
def solve_ac(model: CompiledElectricalModel, options: AcSolveOptions = ...) -> AcSolveReport: ...
