"""Type information for immutable native electrical compilation results."""

from .ac import AcRequest
from .dc import ElectricalInputIdentity, DcOccurrenceCoverage, DcRequest
from .electrical import ContentHash


class CompiledElectricalModel:
    @property
    def identity(self) -> ContentHash: ...
    @property
    def request_identity(self) -> ContentHash: ...
    @property
    def request(self) -> DcRequest: ...
    @property
    def ac_request(self) -> AcRequest | None: ...
    def to_json(self) -> str: ...


class ElectricalCompileReport:
    @property
    def complete(self) -> bool: ...
    @property
    def model(self) -> CompiledElectricalModel | None: ...
    @property
    def coverage(self) -> tuple[DcOccurrenceCoverage, ...]: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
    @property
    def input(self) -> ElectricalInputIdentity: ...
    def to_json(self) -> str: ...


def compile_electrical(request: DcRequest | AcRequest) -> ElectricalCompileReport: ...
