"""Type information for immutable native DC requests."""

from typing import ClassVar, Iterable, Mapping, TypeAlias

from .design import Design
from .electrical import ContentHash, ModelElementKey, Quantity
from .logical import Component, Net

ANALYSIS_DIAGNOSTIC_CODES: frozenset[str]

from .electrical import (ElectricalRequestKey, ElectricalSourceKey, ElectricalProbeKey,
                         ElectricalInputIdentity, ElectricalInput, ElectricalNetRef,
                         ElectricalOccurrenceRef, ElectricalNetPair, prepare_electrical_input)

class _DcVoltageSource:
    @property
    def key(self) -> ElectricalSourceKey: ...
    @property
    def nets(self) -> ElectricalNetPair: ...
    @property
    def value(self) -> Quantity: ...

class _DcCurrentSource:
    @property
    def key(self) -> ElectricalSourceKey: ...
    @property
    def nets(self) -> ElectricalNetPair: ...
    @property
    def value(self) -> Quantity: ...

DcSource: TypeAlias = _DcVoltageSource | _DcCurrentSource

def DcVoltageSource(key: ElectricalSourceKey | str, from_: ElectricalNetRef, to: ElectricalNetRef,
                    value: Quantity) -> _DcVoltageSource: ...
def DcCurrentSource(key: ElectricalSourceKey | str, from_: ElectricalNetRef, to: ElectricalNetRef,
                    value: Quantity) -> _DcCurrentSource: ...

class _DcVoltageProbe:
    @property
    def key(self) -> ElectricalProbeKey: ...
    @property
    def nets(self) -> ElectricalNetPair: ...

def DcVoltageProbe(key: ElectricalProbeKey | str, from_: ElectricalNetRef,
                   to: ElectricalNetRef) -> _DcVoltageProbe: ...

class DcSourceCurrentProbe:
    def __init__(self, key: ElectricalProbeKey | str, source: ElectricalSourceKey | str) -> None: ...
    @property
    def key(self) -> ElectricalProbeKey: ...
    @property
    def source(self) -> ElectricalSourceKey: ...

class DcModelElementCurrentProbe:
    def __init__(self, key: ElectricalProbeKey | str, occurrence: ElectricalOccurrenceRef,
                 element: ModelElementKey | str) -> None: ...
    @property
    def key(self) -> ElectricalProbeKey: ...
    @property
    def occurrence(self) -> ElectricalOccurrenceRef: ...
    @property
    def element(self) -> ModelElementKey: ...

DcProbe: TypeAlias = _DcVoltageProbe | DcSourceCurrentProbe | DcModelElementCurrentProbe

class DcNonElectricalExclusion:
    def __init__(self) -> None: ...

class DcOutsideAnalysisExclusion:
    def __init__(self) -> None: ...

class DcReplacedByStimulusExclusion:
    def __init__(self, sources: Iterable[ElectricalSourceKey | str]) -> None: ...
    @property
    def sources(self) -> tuple[ElectricalSourceKey, ...]: ...

DcExclusionReason: TypeAlias = (DcNonElectricalExclusion | DcOutsideAnalysisExclusion |
                                DcReplacedByStimulusExclusion)

class DcOccurrenceExclusion:
    def __init__(self, occurrence: ElectricalOccurrenceRef, reason: DcExclusionReason) -> None: ...
    @property
    def occurrence(self) -> ElectricalOccurrenceRef: ...
    @property
    def reason(self) -> DcExclusionReason: ...

class DcRequest:
    def __init__(self, key: ElectricalRequestKey | str, input: ElectricalInput,
                 reference: ElectricalNetRef | None = None, sources: Iterable[DcSource] = (),
                 probes: Iterable[DcProbe] = (),
                 exclusions: Iterable[DcOccurrenceExclusion] = ()) -> None: ...
    @property
    def key(self) -> ElectricalRequestKey: ...
    @property
    def input(self) -> ElectricalInput: ...
    @property
    def reference(self) -> ElectricalNetRef | None: ...
    @property
    def sources(self) -> tuple[DcSource, ...]: ...
    @property
    def probes(self) -> tuple[DcProbe, ...]: ...
    @property
    def exclusions(self) -> tuple[DcOccurrenceExclusion, ...]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(input: ElectricalInput, data: bytes | str) -> DcRequest: ...
    def assess(self) -> DcRequestAssessment: ...

class DcCoverageStatus:
    SUPPORTED: ClassVar[DcCoverageStatus]
    EXCLUDED: ClassVar[DcCoverageStatus]
    UNSELECTED: ClassVar[DcCoverageStatus]
    UNRESOLVED: ClassVar[DcCoverageStatus]
    MODEL_ABSENT: ClassVar[DcCoverageStatus]
    UNSUPPORTED: ClassVar[DcCoverageStatus]

class DcOccurrenceCoverage:
    @property
    def occurrence(self) -> ElectricalOccurrenceRef: ...
    @property
    def status(self) -> DcCoverageStatus: ...
    @property
    def selected_part(self) -> Mapping[str, str] | None: ...
    @property
    def exclusion(self) -> DcOccurrenceExclusion | None: ...

class DcRequestAssessment:
    @property
    def complete(self) -> bool: ...
    @property
    def input(self) -> ElectricalInputIdentity: ...
    @property
    def coverage(self) -> tuple[DcOccurrenceCoverage, ...]: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...

def assess_dc_request(request: DcRequest) -> DcRequestAssessment: ...
