"""Type information for immutable native DC requests."""

from typing import ClassVar, Iterable, Mapping, TypeAlias

from .design import Design
from .electrical import ContentHash, ModelElementKey, Quantity
from .logical import Component, Net

ANALYSIS_DIAGNOSTIC_CODES: frozenset[str]

class DcRequestKey:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class DcSourceKey:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class DcProbeKey:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class DcInputIdentity:
    @property
    def logical(self) -> ContentHash: ...
    @property
    def selected_parts(self) -> ContentHash: ...

class DcNetRef:
    @property
    def index(self) -> int: ...
    @property
    def input(self) -> DcInputIdentity: ...

class DcOccurrenceRef:
    @property
    def index(self) -> int: ...
    @property
    def input(self) -> DcInputIdentity: ...

class DcInput:
    @property
    def identity(self) -> DcInputIdentity: ...
    @property
    def nets(self) -> tuple[DcNetRef, ...]: ...
    @property
    def occurrences(self) -> tuple[DcOccurrenceRef, ...]: ...
    def net(self, net: Net) -> DcNetRef: ...
    def occurrence(self, component: Component) -> DcOccurrenceRef: ...

class DcNetPair:
    def __init__(self, from_: DcNetRef, to: DcNetRef) -> None: ...
    @property
    def from_(self) -> DcNetRef: ...
    @property
    def to(self) -> DcNetRef: ...

class _DcVoltageSource:
    @property
    def key(self) -> DcSourceKey: ...
    @property
    def nets(self) -> DcNetPair: ...
    @property
    def value(self) -> Quantity: ...

class _DcCurrentSource:
    @property
    def key(self) -> DcSourceKey: ...
    @property
    def nets(self) -> DcNetPair: ...
    @property
    def value(self) -> Quantity: ...

DcSource: TypeAlias = _DcVoltageSource | _DcCurrentSource

def DcVoltageSource(key: DcSourceKey | str, from_: DcNetRef, to: DcNetRef,
                    value: Quantity) -> _DcVoltageSource: ...
def DcCurrentSource(key: DcSourceKey | str, from_: DcNetRef, to: DcNetRef,
                    value: Quantity) -> _DcCurrentSource: ...

class _DcVoltageProbe:
    @property
    def key(self) -> DcProbeKey: ...
    @property
    def nets(self) -> DcNetPair: ...

def DcVoltageProbe(key: DcProbeKey | str, from_: DcNetRef,
                   to: DcNetRef) -> _DcVoltageProbe: ...

class DcSourceCurrentProbe:
    def __init__(self, key: DcProbeKey | str, source: DcSourceKey | str) -> None: ...
    @property
    def key(self) -> DcProbeKey: ...
    @property
    def source(self) -> DcSourceKey: ...

class DcModelElementCurrentProbe:
    def __init__(self, key: DcProbeKey | str, occurrence: DcOccurrenceRef,
                 element: ModelElementKey | str) -> None: ...
    @property
    def key(self) -> DcProbeKey: ...
    @property
    def occurrence(self) -> DcOccurrenceRef: ...
    @property
    def element(self) -> ModelElementKey: ...

DcProbe: TypeAlias = _DcVoltageProbe | DcSourceCurrentProbe | DcModelElementCurrentProbe

class DcNonElectricalExclusion:
    def __init__(self) -> None: ...

class DcOutsideAnalysisExclusion:
    def __init__(self) -> None: ...

class DcReplacedByStimulusExclusion:
    def __init__(self, sources: Iterable[DcSourceKey | str]) -> None: ...
    @property
    def sources(self) -> tuple[DcSourceKey, ...]: ...

DcExclusionReason: TypeAlias = (DcNonElectricalExclusion | DcOutsideAnalysisExclusion |
                                DcReplacedByStimulusExclusion)

class DcOccurrenceExclusion:
    def __init__(self, occurrence: DcOccurrenceRef, reason: DcExclusionReason) -> None: ...
    @property
    def occurrence(self) -> DcOccurrenceRef: ...
    @property
    def reason(self) -> DcExclusionReason: ...

class DcRequest:
    def __init__(self, key: DcRequestKey | str, input: DcInput,
                 reference: DcNetRef | None = None, sources: Iterable[DcSource] = (),
                 probes: Iterable[DcProbe] = (),
                 exclusions: Iterable[DcOccurrenceExclusion] = ()) -> None: ...
    @property
    def key(self) -> DcRequestKey: ...
    @property
    def input(self) -> DcInput: ...
    @property
    def reference(self) -> DcNetRef | None: ...
    @property
    def sources(self) -> tuple[DcSource, ...]: ...
    @property
    def probes(self) -> tuple[DcProbe, ...]: ...
    @property
    def exclusions(self) -> tuple[DcOccurrenceExclusion, ...]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(input: DcInput, data: bytes | str) -> DcRequest: ...
    def assess(self) -> DcRequestAssessment: ...

class DcCoverageStatus:
    SUPPORTED: ClassVar[DcCoverageStatus]
    EXCLUDED: ClassVar[DcCoverageStatus]
    UNSELECTED: ClassVar[DcCoverageStatus]
    UNRESOLVED: ClassVar[DcCoverageStatus]
    MODEL_ABSENT: ClassVar[DcCoverageStatus]
    UNSUPPORTED: ClassVar[DcCoverageStatus]

class DcOccurrenceCoverage:
    @property
    def occurrence(self) -> DcOccurrenceRef: ...
    @property
    def status(self) -> DcCoverageStatus: ...
    @property
    def selected_part(self) -> Mapping[str, str] | None: ...
    @property
    def exclusion(self) -> DcOccurrenceExclusion | None: ...

class DcRequestAssessment:
    @property
    def complete(self) -> bool: ...
    @property
    def input(self) -> DcInputIdentity: ...
    @property
    def coverage(self) -> tuple[DcOccurrenceCoverage, ...]: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...

def prepare_dc_input(design: Design) -> DcInput: ...
def assess_dc_request(request: DcRequest) -> DcRequestAssessment: ...
