"""Type information for immutable native linear DC solve options and results."""

from typing import ClassVar

from .compilation import CompiledElectricalModel
from .dc import ElectricalProbeKey
from .electrical import ContentHash, Quantity


class DcSolveOptions:
    def __init__(
        self,
        relative_rank_threshold: float = 1e-12,
        minimum_reciprocal_condition: float = 1e-12,
        relative_residual_tolerance: float = 1e-9,
        absolute_voltage_tolerance: Quantity = ...,
        absolute_current_tolerance: Quantity = ...,
    ) -> None: ...
    @property
    def relative_rank_threshold(self) -> float: ...
    @property
    def minimum_reciprocal_condition(self) -> float: ...
    @property
    def relative_residual_tolerance(self) -> float: ...
    @property
    def absolute_voltage_tolerance(self) -> Quantity: ...
    @property
    def absolute_current_tolerance(self) -> Quantity: ...
    @property
    def scaling(self) -> str: ...


class DcSolveOutcome:
    SUCCESS: ClassVar[DcSolveOutcome]
    RANK_DEFICIENT: ClassVar[DcSolveOutcome]
    INCONSISTENT: ClassVar[DcSolveOutcome]
    ILL_CONDITIONED: ClassVar[DcSolveOutcome]
    NUMERICAL_FAILURE: ClassVar[DcSolveOutcome]
    RESIDUAL_FAILURE: ClassVar[DcSolveOutcome]


class DcSolveMetrics:
    @property
    def coordinate_count(self) -> int: ...
    @property
    def rank(self) -> int | None: ...
    @property
    def augmented_rank(self) -> int | None: ...
    @property
    def reciprocal_condition(self) -> float | None: ...
    @property
    def scaled_residual(self) -> float | None: ...
    @property
    def voltage_residual(self) -> Quantity | None: ...
    @property
    def current_residual(self) -> Quantity | None: ...
    @property
    def voltage_error_ratio(self) -> float | None: ...
    @property
    def current_error_ratio(self) -> float | None: ...


class DcNodeResult:
    @property
    def node(self) -> int: ...
    @property
    def potential(self) -> Quantity: ...


class DcBranchResult:
    @property
    def branch(self) -> int: ...
    @property
    def voltage(self) -> Quantity: ...
    @property
    def current(self) -> Quantity: ...
    @property
    def power(self) -> Quantity: ...


class DcProbeResult:
    @property
    def key(self) -> ElectricalProbeKey: ...
    @property
    def value(self) -> Quantity: ...


class DcSolution:
    @property
    def provenance(self) -> DcSolveProvenance: ...
    @property
    def analysis_identity(self) -> ContentHash: ...
    @property
    def model(self) -> CompiledElectricalModel: ...
    @property
    def options(self) -> DcSolveOptions: ...
    @property
    def nodes(self) -> tuple[DcNodeResult, ...]: ...
    @property
    def branches(self) -> tuple[DcBranchResult, ...]: ...
    @property
    def probes(self) -> tuple[DcProbeResult, ...]: ...
    def to_json(self) -> str: ...


class DcSolveReport:
    @property
    def provenance(self) -> DcSolveProvenance: ...
    @property
    def contract_version(self) -> int: ...
    @property
    def backend(self) -> str: ...
    @property
    def analysis_identity(self) -> ContentHash: ...
    @property
    def model(self) -> CompiledElectricalModel: ...
    @property
    def options(self) -> DcSolveOptions: ...
    @property
    def outcome(self) -> DcSolveOutcome: ...
    @property
    def success(self) -> bool: ...
    @property
    def metrics(self) -> DcSolveMetrics: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
    @property
    def solution(self) -> DcSolution | None: ...
    def to_json(self) -> str: ...


def solve_dc(
    model: CompiledElectricalModel, options: DcSolveOptions = ...
) -> DcSolveReport: ...


class DcSolveProvenance:
    @property
    def backend(self) -> str: ...
    @property
    def backend_version(self) -> str: ...
    @property
    def adapter(self) -> str: ...
    @property
    def adapter_contract_version(self) -> int: ...
    @property
    def effective_settings(self) -> str: ...
    @property
    def acceptance_policy(self) -> str: ...
    @property
    def validation_backend(self) -> str: ...
    @property
    def deck_identity(self) -> ContentHash | None: ...
    @property
    def mapping_identity(self) -> ContentHash | None: ...


class NgspiceDcAnalysis:
    @property
    def model(self) -> CompiledElectricalModel: ...
    @property
    def complete(self) -> bool: ...
    @property
    def deck(self) -> str: ...
    @property
    def deck_identity(self) -> ContentHash: ...
    @property
    def mapping_identity(self) -> ContentHash: ...
    @property
    def maximum_output_bytes(self) -> int: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
    def to_json(self) -> str: ...


def prepare_ngspice_dc(model: CompiledElectricalModel) -> NgspiceDcAnalysis: ...


def solve_ngspice_dc(
    analysis: NgspiceDcAnalysis, output: bytes, options: DcSolveOptions = ...
) -> DcSolveReport: ...
