"""Type information for the native passive-model bindings."""

from enum import Enum
from typing import Iterable, Self, TypeAlias, overload

class UnitDimension(Enum):
    RESISTANCE = ...
    CAPACITANCE = ...
    INDUCTANCE = ...
    VOLTAGE = ...
    CURRENT = ...
    POWER = ...
    FREQUENCY = ...
    TIME = ...
    TEMPERATURE = ...
    RATIO = ...

class ToleranceMode(Enum):
    ABSOLUTE = ...
    PERCENT = ...

class Quantity:
    def __init__(self, dimension: UnitDimension, value: float) -> None: ...
    @property
    def dimension(self) -> UnitDimension: ...
    @property
    def value(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...

class Tolerance:
    @staticmethod
    def absolute(minus: Quantity, plus: Quantity) -> Tolerance: ...
    @staticmethod
    @overload
    def percent(value: float) -> Tolerance: ...
    @staticmethod
    @overload
    def percent(minus: float, plus: float) -> Tolerance: ...
    @property
    def mode(self) -> ToleranceMode: ...
    @property
    def minus(self) -> Quantity: ...
    @property
    def plus(self) -> Quantity: ...

class QuantityRange:
    @staticmethod
    def bounded(minimum: Quantity, maximum: Quantity) -> QuantityRange: ...
    @staticmethod
    def at_least(minimum: Quantity) -> QuantityRange: ...
    @staticmethod
    def at_most(maximum: Quantity) -> QuantityRange: ...
    @property
    def dimension(self) -> UnitDimension: ...
    @property
    def minimum(self) -> Quantity | None: ...
    @property
    def maximum(self) -> Quantity | None: ...

class ContentHash:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PinKey:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class ModelTerminalKey:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class ModelInternalNodeKey:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class ModelElementKey:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

_ModelEndpoint: TypeAlias = ModelTerminalKey | ModelInternalNodeKey

class ModelTerminal:
    def __init__(self, key: ModelTerminalKey | str, pin: PinKey | str) -> None: ...
    @property
    def key(self) -> ModelTerminalKey: ...
    @property
    def pin(self) -> PinKey: ...

class ModelInternalNode:
    def __init__(self, key: ModelInternalNodeKey | str) -> None: ...
    @property
    def key(self) -> ModelInternalNodeKey: ...

class ModelParameter:
    def __init__(self, nominal: Quantity, tolerance: Tolerance | None = None,
                 evidence: Iterable[ContentHash | str] = ()) -> None: ...
    @property
    def nominal(self) -> Quantity: ...
    @property
    def tolerance(self) -> Tolerance | None: ...
    @property
    def bounds(self) -> QuantityRange | None: ...
    @property
    def evidence(self) -> tuple[ContentHash, ...]: ...

class ResistanceElement:
    def __init__(self, key: ModelElementKey | str, from_: _ModelEndpoint,
                 to: _ModelEndpoint, parameter: ModelParameter) -> None: ...
    @property
    def key(self) -> ModelElementKey: ...
    @property
    def from_(self) -> _ModelEndpoint: ...
    @property
    def to(self) -> _ModelEndpoint: ...
    @property
    def parameter(self) -> ModelParameter: ...

class CapacitanceElement:
    def __init__(self, key: ModelElementKey | str, from_: _ModelEndpoint,
                 to: _ModelEndpoint, parameter: ModelParameter) -> None: ...
    @property
    def key(self) -> ModelElementKey: ...
    @property
    def from_(self) -> _ModelEndpoint: ...
    @property
    def to(self) -> _ModelEndpoint: ...
    @property
    def parameter(self) -> ModelParameter: ...

class InductanceElement:
    def __init__(self, key: ModelElementKey | str, from_: _ModelEndpoint,
                 to: _ModelEndpoint, parameter: ModelParameter) -> None: ...
    @property
    def key(self) -> ModelElementKey: ...
    @property
    def from_(self) -> _ModelEndpoint: ...
    @property
    def to(self) -> _ModelEndpoint: ...
    @property
    def parameter(self) -> ModelParameter: ...

_ModelElement: TypeAlias = ResistanceElement | CapacitanceElement | InductanceElement

class PartElectricalModel:
    @property
    def implemented_component(self) -> ContentHash: ...
    @property
    def terminals(self) -> tuple[ModelTerminal, ...]: ...
    @property
    def internal_nodes(self) -> tuple[ModelInternalNode, ...]: ...
    @property
    def elements(self) -> tuple[_ModelElement, ...]: ...

class ModelTerminalHandle:
    @property
    def key(self) -> ModelTerminalKey: ...
    def belongs_to(self, builder: PartElectricalModelBuilder) -> bool: ...

class ModelInternalNodeHandle:
    @property
    def key(self) -> ModelInternalNodeKey: ...
    def belongs_to(self, builder: PartElectricalModelBuilder) -> bool: ...

_ModelBuilderEndpoint: TypeAlias = ModelTerminalHandle | ModelInternalNodeHandle

class PartElectricalModelBuilder:
    def __init__(self, component_payload: dict[str, object]) -> None: ...
    def terminal(self, key: ModelTerminalKey | str, pin: PinKey | str) -> ModelTerminalHandle: ...
    def internal_node(self, key: ModelInternalNodeKey | str) -> ModelInternalNodeHandle: ...
    def resistance(self, key: ModelElementKey | str, from_: _ModelBuilderEndpoint,
                   to: _ModelBuilderEndpoint, parameter: ModelParameter) -> Self: ...
    def capacitance(self, key: ModelElementKey | str, from_: _ModelBuilderEndpoint,
                    to: _ModelBuilderEndpoint, parameter: ModelParameter) -> Self: ...
    def inductance(self, key: ModelElementKey | str, from_: _ModelBuilderEndpoint,
                   to: _ModelBuilderEndpoint, parameter: ModelParameter) -> Self: ...
    def build(self) -> PartElectricalModel: ...

def ohms(value: float) -> Quantity: ...
def farads(value: float) -> Quantity: ...
def henries(value: float) -> Quantity: ...
def hertz(value: float) -> Quantity: ...
def seconds(value: float) -> Quantity: ...
def content_hash(data: bytes) -> str: ...
