from typing import ClassVar, Iterable
from .electrical import ElectricalInput, ElectricalInputIdentity, ElectricalNetRef, ElectricalOccurrenceRef, ElectricalRequestKey, ElectricalSourceKey, ElectricalNetPair, Quantity, UnitDimension, ContentHash
from .dc import DcProbe, DcOccurrenceExclusion, DcOccurrenceCoverage
from .dc_solve import DcSolution, DcSolveReport
class TransientTimeGrid:
    def __init__(self, times: Iterable[Quantity]) -> None: ...
    @staticmethod
    def uniform(horizon: Quantity, count: int) -> TransientTimeGrid: ...
    @property
    def times(self) -> tuple[Quantity, ...]: ...
    @property
    def horizon(self) -> Quantity: ...
class TransientWaveformKnot:
    def __init__(self, time: Quantity, value: Quantity) -> None: ...
    @property
    def time(self) -> Quantity: ...
    @property
    def value(self) -> Quantity: ...
class TransientWaveform:
    def __init__(self, constant: Quantity | Iterable[TransientWaveformKnot]) -> None: ...
    @property
    def constant(self) -> bool: ...
    @property
    def dimension(self) -> UnitDimension: ...
    @property
    def knots(self) -> tuple[TransientWaveformKnot, ...]: ...
    def value_at(self, time: Quantity) -> Quantity: ...
class TransientStorageKind:
    CAPACITOR_VOLTAGE: ClassVar[TransientStorageKind]
    INDUCTOR_CURRENT: ClassVar[TransientStorageKind]
class TransientDcProvenance:
    @property
    def input(self) -> ElectricalInputIdentity: ...
    @property
    def analysis_identity(self) -> ContentHash: ...
    @property
    def participation_identity(self) -> ContentHash: ...
    @property
    def storage_count(self) -> int: ...
class TransientInitialState:
    def __init__(self, input: ElectricalInput, occurrence: ElectricalOccurrenceRef, element: str, kind: TransientStorageKind, value: Quantity) -> None: ...
    @property
    def occurrence(self) -> ElectricalOccurrenceRef: ...
    @property
    def part(self) -> dict[str, str]: ...
    @property
    def element(self) -> str: ...
    @property
    def kind(self) -> TransientStorageKind: ...
    @property
    def value(self) -> Quantity: ...
class TransientInitialConditions:
    def __init__(self, entries: Iterable[TransientInitialState] = ()) -> None: ...
    @property
    def entries(self) -> tuple[TransientInitialState, ...]: ...
    @property
    def dc_provenance(self) -> TransientDcProvenance | None: ...
class TransientVoltageSource:
    def __init__(self, key: str | ElectricalSourceKey, from_: ElectricalNetRef, to: ElectricalNetRef, waveform: TransientWaveform) -> None: ...
    @property
    def key(self) -> ElectricalSourceKey: ...
    @property
    def nets(self) -> ElectricalNetPair: ...
    @property
    def waveform(self) -> TransientWaveform: ...
class TransientCurrentSource:
    def __init__(self, key: str | ElectricalSourceKey, from_: ElectricalNetRef, to: ElectricalNetRef, waveform: TransientWaveform) -> None: ...
    @property
    def key(self) -> ElectricalSourceKey: ...
    @property
    def nets(self) -> ElectricalNetPair: ...
    @property
    def waveform(self) -> TransientWaveform: ...
class TransientRequest:
    def __init__(self, key: str | ElectricalRequestKey, input: ElectricalInput, grid: TransientTimeGrid, *, reference: ElectricalNetRef | None = None, sources: Iterable[TransientVoltageSource | TransientCurrentSource] = (), probes: Iterable[DcProbe] = (), exclusions: Iterable[DcOccurrenceExclusion] = (), initial_state: TransientInitialConditions | Iterable[TransientInitialState] = ()) -> None: ...
    @property
    def key(self) -> ElectricalRequestKey: ...
    @property
    def input(self) -> ElectricalInput: ...
    @property
    def grid(self) -> TransientTimeGrid: ...
    @property
    def reference(self) -> ElectricalNetRef | None: ...
    @property
    def times(self) -> tuple[Quantity, ...]: ...
    @property
    def sources(self) -> tuple[TransientVoltageSource | TransientCurrentSource, ...]: ...
    @property
    def probes(self) -> tuple[DcProbe, ...]: ...
    @property
    def exclusions(self) -> tuple[DcOccurrenceExclusion, ...]: ...
    @property
    def initial_state(self) -> tuple[TransientInitialState, ...]: ...
    @property
    def initial_conditions(self) -> TransientInitialConditions: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(input: ElectricalInput, data: str | bytes) -> TransientRequest: ...
    def assess(self) -> TransientRequestAssessment: ...
class TransientRequestAssessment:
    @property
    def complete(self) -> bool: ...
    @property
    def input(self) -> ElectricalInputIdentity: ...
    @property
    def coverage(self) -> tuple[DcOccurrenceCoverage, ...]: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
def assess_transient_request(request: TransientRequest) -> TransientRequestAssessment: ...
def initial_state_from(solution: DcSolution | DcSolveReport) -> TransientInitialConditions: ...
