from typing import ClassVar
from .electrical import Quantity, ContentHash, ElectricalProbeKey
from .compilation import CompiledElectricalModel
class TransientSolveOptions:
    def __init__(self, minimum_step: Quantity, initial_step: Quantity, maximum_step: Quantity, maximum_trials: int, maximum_accepted_steps: int, relative_temporal_tolerance: float = 1e-4, absolute_temporal_voltage: Quantity = ..., absolute_temporal_current: Quantity = ...) -> None: ...
    @property
    def minimum_step(self) -> Quantity: ...
    @property
    def initial_step(self) -> Quantity: ...
    @property
    def maximum_step(self) -> Quantity: ...
    @property
    def maximum_trials(self) -> int: ...
    @property
    def maximum_accepted_steps(self) -> int: ...
    @property
    def relative_temporal_tolerance(self) -> float: ...
    @property
    def absolute_temporal_voltage(self) -> Quantity: ...
    @property
    def absolute_temporal_current(self) -> Quantity: ...
class TransientSolveOutcome:
    SUCCESS: ClassVar[TransientSolveOutcome]
    INCONSISTENT_INITIAL_STATE: ClassVar[TransientSolveOutcome]
    UNSUPPORTED_INITIALIZATION_TOPOLOGY: ClassVar[TransientSolveOutcome]
    RANK_DEFICIENT: ClassVar[TransientSolveOutcome]
    INCONSISTENT: ClassVar[TransientSolveOutcome]
    ILL_CONDITIONED: ClassVar[TransientSolveOutcome]
    NUMERICAL_FAILURE: ClassVar[TransientSolveOutcome]
    RESIDUAL_FAILURE: ClassVar[TransientSolveOutcome]
    STEP_LIMIT: ClassVar[TransientSolveOutcome]
    WORK_LIMIT: ClassVar[TransientSolveOutcome]
class TransientEvaluationKind:
    INITIALIZATION: ClassVar[TransientEvaluationKind]
    ALGEBRAIC_SAMPLE: ClassVar[TransientEvaluationKind]
    FULL_STEP: ClassVar[TransientEvaluationKind]
    FIRST_HALF: ClassVar[TransientEvaluationKind]
    SECOND_HALF: ClassVar[TransientEvaluationKind]
class TransientAlgebraMetrics:
    @property
    def coordinate_count(self) -> int: ...
    @property
    def rank(self) -> int | None: ...
    @property
    def augmented_rank(self) -> int | None: ...
    @property
    def reciprocal_condition(self) -> float | None: ...
    @property
    def scaled_residual(self) -> float | None: ...
    @property
    def voltage_residual(self) -> Quantity | None: ...
    @property
    def current_residual(self) -> Quantity | None: ...
    @property
    def voltage_error_ratio(self) -> float | None: ...
    @property
    def current_error_ratio(self) -> float | None: ...

class TransientNodeResult:
    @property
    def node(self) -> int: ...
    @property
    def potential(self) -> Quantity: ...
class TransientBranchResult:
    @property
    def branch(self) -> int: ...
    @property
    def voltage(self) -> Quantity: ...
    @property
    def current(self) -> Quantity: ...
    @property
    def power(self) -> Quantity: ...
class TransientProbeResult:
    @property
    def key(self) -> ElectricalProbeKey: ...
    @property
    def value(self) -> Quantity: ...
class TransientStorageDerivative:
    @property
    def branch(self) -> int: ...
    @property
    def derivative(self) -> float: ...
class TransientEvaluation:
    @property
    def time(self) -> Quantity: ...
    @property
    def duration(self) -> Quantity: ...
    @property
    def kind(self) -> TransientEvaluationKind: ...
    @property
    def outcome(self) -> TransientSolveOutcome: ...
    @property
    def metrics(self) -> TransientAlgebraMetrics: ...
    @property
    def normalized_error(self) -> float | None: ...
    @property
    def solve_count(self) -> int: ...
    @property
    def factorization_count(self) -> int: ...
    @property
    def trial_accepted(self) -> bool: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
class TransientAcceptedHalfStep:
    @property
    def time(self) -> Quantity: ...
    @property
    def duration(self) -> Quantity: ...
    @property
    def normalized_error(self) -> float: ...
    @property
    def metrics(self) -> TransientAlgebraMetrics: ...
class TransientSample:
    @property
    def time(self) -> Quantity: ...
    @property
    def nodes(self) -> tuple[TransientNodeResult, ...]: ...
    @property
    def branches(self) -> tuple[TransientBranchResult, ...]: ...
    @property
    def probes(self) -> tuple[TransientProbeResult, ...]: ...
class TransientSolution:
    @property
    def analysis_identity(self) -> ContentHash: ...
    @property
    def model(self) -> CompiledElectricalModel: ...
    @property
    def options(self) -> TransientSolveOptions: ...
    @property
    def samples(self) -> tuple[TransientSample, ...]: ...
    def to_json(self) -> str: ...
class TransientSolveReport:
    @property
    def analysis_identity(self) -> ContentHash: ...
    @property
    def model(self) -> CompiledElectricalModel: ...
    @property
    def options(self) -> TransientSolveOptions: ...
    @property
    def backend(self) -> str: ...
    @property
    def contract_version(self) -> int: ...
    @property
    def outcome(self) -> TransientSolveOutcome: ...
    @property
    def success(self) -> bool: ...
    @property
    def solution(self) -> TransientSolution | None: ...
    @property
    def evaluations(self) -> tuple[TransientEvaluation, ...]: ...
    @property
    def initial_derivatives(self) -> tuple[TransientStorageDerivative, ...]: ...
    @property
    def accepted_half_steps(self) -> tuple[TransientAcceptedHalfStep, ...]: ...
    @property
    def last_accepted_time(self) -> Quantity: ...
    @property
    def trial_count(self) -> int: ...
    @property
    def accepted_step_count(self) -> int: ...
    @property
    def solve_count(self) -> int: ...
    @property
    def factorization_count(self) -> int: ...
    @property
    def diagnostics(self) -> list[dict[str, object]]: ...
    def to_json(self) -> str: ...
def solve_transient(model: CompiledElectricalModel, options: TransientSolveOptions) -> TransientSolveReport: ...
